progressif/main/default/objects/Criterion__c/Criterion__c.object-meta.xml
<CustomObject>
    <label>Critère</label>
    <nameField>
        <label>Nom de Critère</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Critères</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Criterion__c/fields/FormatCriterion__c.field-meta.xml
<CustomField>
    <fullName>FormatCriterion__c</fullName>
    <description>Format du champ pour ce critère. Exemple: Texte de 255, Nombre sur 10</description>
    <inlineHelpText>Format du champ pour ce critère. Exemple: Texte de 255, Nombre sur 10</inlineHelpText>
    <label>Format du critère</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/LabelCriterion__c.field-meta.xml
<CustomField>
    <fullName>LabelCriterion__c</fullName>
    <description>Libellé du critère affiché dans les écrans</description>
    <inlineHelpText>Libellé du critère affiché dans les écrans</inlineHelpText>
    <label>Libellé du critère</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/ListValues__c.field-meta.xml
<CustomField>
    <fullName>ListValues__c</fullName>
    <description>Les valeurs de la Picklist  , exemple (Val1,Val2,.....)</description>
    <inlineHelpText>Les valeurs de la Picklist ,exemple (Val1,Val2,.....)</inlineHelpText>
    <label>Liste des valeurs</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <label>Obligatoire</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Oui</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Cible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/TypeCriterion__c.field-meta.xml
<CustomField>
    <fullName>TypeCriterion__c</fullName>
    <description>Type de champ pour ce critère</description>
    <inlineHelpText>Type de champ pour ce critère</inlineHelpText>
    <label>Type du critère</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Nom de Offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Offer__c/fields/ActivityAreas__c.field-meta.xml
<CustomField>
    <fullName>ActivityAreas__c</fullName>
    <description>Permet de définir les secteurs d&#39;activités concernées par l&#39;offre. Une offre peut concernée plusieurs secteurs d&#39;activités</description>
    <inlineHelpText>Permet de définir les secteurs d&#39;activités concernées par l&#39;offre. Une offre peut concernée plusieurs secteurs d&#39;activités</inlineHelpText>
    <label>Secteur d&#39;activités</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Secteurs_d_activites</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/fields/CdCOnlineProfiles__c.field-meta.xml
<CustomField>
    <fullName>CdCOnlineProfiles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible CdC Online et Réseau</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/CurrentOffer__c.field-meta.xml
<CustomField>
    <fullName>CurrentOffer__c</fullName>
    <formula>IF(ISBLANK( EndingDateValidity__c ),
IF(TODAY() &gt;=  StartingDateValidity__c &amp;&amp;  TECH_NumberOfVenueCriterions__c &gt; 0, true, false ),
IF(TODAY() &gt;=  StartingDateValidity__c &amp;&amp; TODAY() &lt;= EndingDateValidity__c &amp;&amp;  TECH_NumberOfVenueCriterions__c &gt; 0, true, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Offre en vigueur si date du jour comprise dans les dates de validité de l&#39;offre et s&#39;il existe au moins un critère qui a pour cible Point de diffusion</inlineHelpText>
    <label>Offre en vigueur</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/CustomerProfiles__c.field-meta.xml
<CustomField>
    <fullName>CustomerProfiles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible Clients</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <label>Vignette</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/ValueOfferFamily__c.field-meta.xml
<CustomField>
    <fullName>ValueOfferFamily__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Famille d&#39;offre</label>
    <referenceTo>OfferFamily__c</referenceTo>
    <relationshipLabel>Offres</relationshipLabel>
    <relationshipName>ChildOffer</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/OfferCriterion__c.object-meta.xml
<CustomObject>
    <label>Critère de l&#39;offre</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Numéro de Critère</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferCriterion__c/fields/criterion__c.field-meta.xml
<CustomField>
    <fullName>criterion__c</fullName>
    <label>Critère</label>
    <referenceTo>Criterion__c</referenceTo>
    <relationshipLabel>Critères de l&#39;offre</relationshipLabel>
    <relationshipName>ChildCriterion</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/CriterionResponse__c.field-meta.xml
<CustomField>
    <fullName>CriterionResponse__c</fullName>
    <label>Réponse de critère</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/FormatCriterion__c.field-meta.xml
<CustomField>
    <fullName>FormatCriterion__c</fullName>
    <formula>criterion__r.FormatCriterion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Format du critère</label>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/IfResponse__c.field-meta.xml
<CustomField>
    <fullName>IfResponse__c</fullName>
    <label>Si réponse</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MainCriterion__c.field-meta.xml
<CustomField>
    <fullName>MainCriterion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Critère principal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Aucun critère de l&#39;offre trouvé</errorMessage>
        <filterItems>
            <field>$Source.Offer__c</field>
            <operation>equals</operation>
            <valueField>OfferCriterion__c.Offer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OfferCriterion__c</referenceTo>
    <relationshipLabel>Critères secondaires</relationshipLabel>
    <relationshipName>ChildSecondaryCriterionOfferCriterion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obligatoire</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Maxlength__c.field-meta.xml
<CustomField>
    <fullName>Maxlength__c</fullName>
    <label>Nbr de caractères maximal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageRangeOverFlow__c.field-meta.xml
<CustomField>
    <fullName>MessageRangeOverFlow__c</fullName>
    <label>Message erreur max</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageRangeUnderFlow__c.field-meta.xml
<CustomField>
    <fullName>MessageRangeUnderFlow__c</fullName>
    <label>Message d&#39;erreur min</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageValueMissing__c.field-meta.xml
<CustomField>
    <fullName>MessageValueMissing__c</fullName>
    <label>Message d&#39;erreur obligatoire</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageWhenTooLong__c.field-meta.xml
<CustomField>
    <fullName>MessageWhenTooLong__c</fullName>
    <label>Message erreur maxlength</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageWhenTooShort__c.field-meta.xml
<CustomField>
    <fullName>MessageWhenTooShort__c</fullName>
    <label>Message erreur minlength</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Minimum__c.field-meta.xml
<CustomField>
    <fullName>Minimum__c</fullName>
    <label>Minimum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Minlength__c.field-meta.xml
<CustomField>
    <fullName>Minlength__c</fullName>
    <label>Nbr de caractères minimal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipName>Crit_res</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/OrderDisplay__c.field-meta.xml
<CustomField>
    <fullName>OrderDisplay__c</fullName>
    <inlineHelpText>Bonne pratique : saisissez comme ordre d&#39;affichage 10, 20 plutôt que 1, 2. Ainsi, vous pourrez insérer un critère plus tard sans devoir changer la numérotation !</inlineHelpText>
    <label>Ordre d&#39;affichage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferFamily__c/OfferFamily__c.object-meta.xml
<CustomObject>
    <label>Famille d&#39;offre</label>
    <nameField>
        <label>Famille d&#39;offre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familles d&#39;offre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferFamily__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <formula>if(ISBLANK(  Url__c  ), &quot;&quot;, IMAGE(Url__c, &quot;Picture&quot;, 200, 200))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

progressif/main/default/globalValueSets/Secteurs_d_activites.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AEROPORT</fullName>
    </customValue>
    <customValue>
        <fullName>Agences événementielles</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPING</fullName>
    </customValue>
    <customValue>
        <fullName>CASINO</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>CINEMAS</fullName>
    </customValue>
    <customValue>
        <fullName>CIRQUES</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE DE DETAIL</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE DE DETAIL de DISQUES</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE GRANDE DISTRIBUTION</fullName>
    </customValue>
    <customValue>
        <fullName>EDITION &amp; COMMUNICATION</fullName>
    </customValue>
    <customValue>
        <fullName>EDS</fullName>
    </customValue>
    <customValue>
        <fullName>EDS / CABARET</fullName>
    </customValue>
    <customValue>
        <fullName>ENSEIGNEMENT</fullName>
    </customValue>
    <customValue>
        <fullName>ENTREPRISE &amp; ADMINISTRATION</fullName>
    </customValue>
    <customValue>
        <fullName>EQUIPEMENT SPORTIF</fullName>
    </customValue>
    <customValue>
        <fullName>ETABL CULTUREL</fullName>
    </customValue>
    <customValue>
        <fullName>ETABL SANTE</fullName>
    </customValue>
    <customValue>
        <fullName>EXPLOITANT PARKING</fullName>
    </customValue>
    <customValue>
        <fullName>HEBERGEMENT TOURISTIQUE</fullName>
    </customValue>
    <customValue>
        <fullName>Institutions sociales</fullName>
    </customValue>
    <customValue>
        <fullName>KARTING</fullName>
    </customValue>
    <customValue>
        <fullName>Organisateur événementiel occasionnel</fullName>
    </customValue>
    <customValue>
        <fullName>PARC d&#39;ATTRACTIONS ou de LOISIRS</fullName>
    </customValue>
    <customValue>
        <fullName>PRODUCTEUR de SPECTACLES</fullName>
    </customValue>
    <customValue>
        <fullName>PRODUCTEUR PHONO VIDEO</fullName>
    </customValue>
    <customValue>
        <fullName>SALLES de JEUX ARCADES</fullName>
    </customValue>
    <customValue>
        <fullName>SALON DE COIFFURE</fullName>
    </customValue>
    <masterLabel>Secteurs d&#39;activités</masterLabel>
</GlobalValueSet>

progressif/main/default/globalValueSets/Target.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Espace de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Moyen de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Point de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Autre</fullName>
        <isActive>false</isActive>
        <label>Autre</label>
    </customValue>
    <masterLabel>Cible</masterLabel>
</GlobalValueSet>

progressif/main/default/classes/LCCTRL_OfferController.cls
public class LCCTRL_OfferController {

    @AuraEnabled(cacheable=true)
        public static User getUserDetails(String recId) {
            return  [Select Id , Name ,ProfileId,Profile.name from User where Id =:recId];
        }
    

    @AuraEnabled(Cacheable = true)
    public static List<OfferFamily__c>  findOfferFamily(){
        try{
            // Gérer le filtre pour la visibilité des offres par profils 
            Profile CurrentProfile = [select id , name from profile where id=:userinfo.getProfileId() limit 1];
            
            
            //Profil client + Admin
            boolean IsVisibleCustomer;
            
             if (CurrentProfile.Name== 'Customer Community Plus Login User SACEM'   || CurrentProfile.Name=='Customer Community Plus Login User' 
                ||  CurrentProfile.Name== 'System Administrator' ||  CurrentProfile.Name =='Administrateur système'){
             IsVisibleCustomer = true   ;
            }
            
            // Profil onLine et réseau  + Admin
            boolean IsVisibleInternal;
            
            if (CurrentProfile.Name=='Chargé de clientèle réseau'|| CurrentProfile.Name== 'Chargé de clientèle online' 
                ||  CurrentProfile.Name== 'System Administrator' ||  CurrentProfile.Name== 'Administrateur système' ){
             IsVisibleInternal  = true; 
            }

            system.debug('rso visibvilité'+IsVisibleCustomer+ IsVisibleInternal);	
            List<OfferFamily__c> listOfferFamilyAll=new List <OfferFamily__c>();
            listOfferFamilyAll = [SELECT Id,Name,Picture__c ,Url__c , description__c , 
                               (select id , name , customerProfiles__c, cdconlineProfiles__c 
                                from childoffer__r 
                                where (customerProfiles__c=:IsVisibleCustomer or cdconlineProfiles__c=:IsVisibleInternal) )

                               FROM OfferFamily__c];
            
             List<OfferFamily__c> listOfferFamilyFiltred=new List <OfferFamily__c>();
            
            for ( OfferFamily__c family:listOfferFamilyAll ){
                
                system.debug('rso child family'+family.childoffer__r.size());
                if (family.childoffer__r.size()>0 ){
                    listOfferFamilyFiltred.add(family);
                }
            }
            
            system.debug('rso retour filtre family'+listOfferFamilyFiltred);
            return listOfferFamilyFiltred; 
            
        } 
        catch(Exception e) {
            
            System.debug('An exception occurred: ' + e.getMessage());
            return null;
        }   
    }
    
 
    @AuraEnabled(Cacheable = true)
    public static List<Offer__c>  getOffers(){
        try{
            List<Offer__c> listOffer = new List<Offer__c>();
            
            listOffer  =[SELECT Id, name FROM Offer__c];
            
            return listOffer; 
            
        } 
        catch(Exception e) {
            
            System.debug('An exception occurred: ' + e.getMessage());
            return null;
        }   
    }
    
	/*    
    @auraEnabled 
    public static List<Offer__c>  getOffersById(){
        try{
            List<Offer__c> listOfferById = new List<Offer__c>();
            
            listOfferById = [SELECT Id, name FROM Offer__c WHERE Id IN ('a0L6E000003fgQQUAY','a0L6E000003fgQfUAI','a0L6E000003fgQVUAY')];
            
            return listOfferById; 
            
        } 
        catch(Exception e) {
            
            System.debug('An exception occurred: ' + e.getMessage());
            return null;
        }   
    }
*/
    
    @auraEnabled 
    public static List<Offer__c>  getOffersByFamily(Id RecordId){
        try{
            List<Offer__c> listFamilyOff = new List<Offer__c>();
            
            listFamilyOff  =[SELECT Id, name,CurrentOffer__c  ,ActivityAreas__c ,ValueOfferFamily__c  FROM Offer__c WHERE ValueOfferFamily__c =:RecordId ];
           
            return listFamilyOff; 
            
        } 
        catch(Exception e) {
            
            System.debug('An exception occurred: ' + e.getMessage());
            return null;
        }   
    }
    
    
    
    @auraEnabled (Cacheable = true)
    public static List<OfferCriterion__c> getCriteres (Id RecordId){
        
        List<OfferCriterion__c> crits= new list <OfferCriterion__c>();
        
        crits = [SELECT Id, MessageRangeUnderFlow__c,MessageValueMissing__c , MessageRangeOverFlow__c ,CriterionResponse__c ,criterion__r.Name,criterion__r.Target__c, criterion__r.LabelCriterion__c , criterion__r.TypeCriterion__c , criterion__r.FormatCriterion__c, 
                 criterion__r.ListValues__c, Mandatory__c,Offer__c , Maxlength__c,Minlength__c,Maximum__c , MessageWhenTooLong__c ,Minimum__c, MessageWhenTooShort__c , OrderDisplay__c, 
                 (SELECT Id,Name, criterion__r.Name, criterion__r.LabelCriterion__c , criterion__r.TypeCriterion__c , criterion__r.FormatCriterion__c, 
                 criterion__r.ListValues__c , Mandatory__c ,Offer__c , Maxlength__c ,Minlength__c ,Maximum__c ,MessageWhenTooLong__c,Minimum__c,MessageWhenTooShort__c, OrderDisplay__c , IfResponse__c , MessageRangeUnderFlow__c ,MessageValueMissing__c, MessageRangeOverFlow__c  
                 FROM ChildSecondaryCriterionOfferCriterion__r )
                 FROM OfferCriterion__c 
                 WHERE Offer__c =:RecordId AND status__c='Principal' AND criterion__r.Target__c='Standard'
                 ORDER BY  OrderDisplay__c ASC];
        
        return crits;

    }
    
    @auraEnabled 
    public static List<OfferCriterion__c> getCaneaux (Id RecordId){
        
        List<OfferCriterion__c> caneaux= new list <OfferCriterion__c>();
        
        caneaux = [SELECT Id, CriterionResponse__c  ,criterion__r.Name,criterion__r.Target__c, criterion__r.LabelCriterion__c , criterion__r.TypeCriterion__c , criterion__r.FormatCriterion__c, 
                 criterion__r.ListValues__c ,Maxlength__c,MessageWhenTooLong__c ,Minlength__c,MessageWhenTooShort__c, Mandatory__c,Offer__c , Maximum__c ,Minimum__c, OrderDisplay__c 
                 FROM OfferCriterion__c 
                 WHERE Offer__c =:RecordId AND status__c='Principal' AND criterion__r.target__c in ('Espace de diffusion','Moyen de diffusion')
                 ORDER BY  OrderDisplay__c  ASC];
        
        return caneaux;

    }
    
    //Get Offer Area activity Picklist Values
    @auraEnabled (Cacheable = true)
    public static Map<String, String> getActivityArea(){
        Map<String, String> options = new Map<String, String>();
        //get Offer area activity Field Describe
        Schema.DescribeFieldResult fieldResult = Offer__c.ActivityAreas__c.getDescribe();
        //get Offer area activity Picklist Values
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            //Put Picklist Value & Label in Map
            options.put(p.getValue(), p.getLabel());
        }
        
        //system.debug('Area : '+ options );
        return options;
    }
    
    // Get Primary Criterion Options

    @AuraEnabled
    public static OfferCriterion__c  getOptionsPicklist(id RecordId){
   	//get criterion Picklist Values
        OfferCriterion__c  Criterion = [ SELECT id , criterion__r.ListValues__c,Offer__c,criterion__r.TypeCriterion__c  FROM OfferCriterion__c   WHERE id =:RecordId]; 
		return Criterion;
    }    
       
    @AuraEnabled
    public static asset saveAutorisation(string RecordId , string Offer , string Criteres , string  Espaces){
        
        try {
            if(RecordId.countMatches('a0a')==0)    {
                
               Contracts__c  c  = new Contracts__c (); 
               c.AccountName__c = '0011w00000HxcAEAAZ';
               c.Status__c 	    ='En cours';
               c.ContractStartingDate__c = date.newInstance(2019, 10, 21);
               c.ClosingDate__c          = date.newInstance(2019, 11, 21);
                
               insert c;
               RecordId = c.Id; 
            }  
            
            //L'offre sélectionné
            Offer__c o = new Offer__c();
            o = [SELECT id , name FROM Offer__c WHERE id =:Offer LIMIT 1];
            
            //Le contract encours
            Contracts__c  c = new Contracts__c ();
            c = [SELECT id , AccountName__c  FROM Contracts__c  WHERE id=:RecordId LIMIT 1];
            
            //Créer Asset
            asset a        = new asset();
            a.Contracts__c = RecordId;
            a.AccountId    = c.AccountName__c ;
            a.Offre__c     = Offer;
            a.Name		   = o.Name;
             system.debug ( 'insert a' + a);
            insert a;
            
            //Créer Critères autorisation Standard
            system.debug('CritListJson input : ' + Criteres);
            
            List <JSON2ApexCriterion> criteresparser=(List<JSON2ApexCriterion>)JSON.deserialize(Criteres,List<JSON2ApexCriterion>.class);
            List<CriterionAuthorization__c> CriterestoInsert = new List<CriterionAuthorization__c>();
            for (JSON2ApexCriterion crit:criteresparser ){
                //system.debug('test item crit '+crit.Id + 'val ' + crit.Value);
                CriterestoInsert.add( new CriterionAuthorization__c  (Authorization__c=a.id,CriterionOffer__c=crit.Id,CriterionResponseAuthz__c = crit.Value));
            }
                     
           
            //Créer Espaces 
            system.debug('EspacesJson input : ' + Espaces);
            
            List <JSON2ApexEspace> espacesparser=(List<JSON2ApexEspace>)JSON.deserialize(Espaces,List<JSON2ApexEspace>.class);
            
            //List <BroadcastSpace__c> EspacestoInsert = new List<BroadcastSpace__c>();
            for (JSON2ApexEspace Espace:espacesparser ){
                //system.debug('test item Espace '+Espace.Key);
                //EspacestoInsert.add ( new broadcast_space__c ( Autorisation__c=a.Id,Name= string.valueOf(Espace.Key)));
                BroadcastSpace__c  EspaceToinsert= new BroadcastSpace__c();
                EspaceToinsert.Authorization__c = a.Id;
                EspaceToinsert.Name=string.valueOf(Espace.Key);
                insert EspaceToinsert;
                
                for (JSON2ApexCriterion crit:Espace.Criteres ){
                 system.debug('Espace Crit'+crit) ;
                 CriterestoInsert.add( new CriterionAuthorization__c  (Authorization__c=a.id,CriterionOffer__c=crit.Id,
                                                                          CriterionResponseAuthz__c  = crit.Value,
																		  BroadcastSpace__c  = EspaceToinsert.Id
                                                                         ));
           
                }
                for (JSON2ApexMoyen moyen:Espace.Moyens ){
                    //system.debug('Espace Moyen'+moyen) ;
                    
                    WayDiffusion__c  MoyenToinsert  = new WayDiffusion__c();
                    MoyenToinsert.BroadcastSpace__c = EspaceToinsert.Id;
                    MoyenToinsert.Name=string.valueOf(moyen.Key);
                    //MoyenToinsert.Autorisation__c=a.Id;
                    
                    insert MoyenToinsert;
                    
                     for (JSON2ApexCriterion crit:moyen.Criteres ){
                     //system.debug('Moyen Crit'+crit) ;
                     CriterestoInsert.add( new CriterionAuthorization__c  (Authorization__c=a.id,CriterionOffer__c =crit.Id,
                                                                              CriterionResponseAuthz__c  = crit.Value,
                                                                              BroadcastSpace__c   = EspaceToinsert.Id,
                                                                              WayDiffusion__c  =MoyenToinsert.Id
                                                                             ));
           
                }
                    
                    
                }
                
                
             }
          
            
              //system.debug(CriterestoInsert.size());
             if (CriterestoInsert.size()>0 ){
                insert CriterestoInsert;
            }
            
            
            asset newasset = [SELECT id , name , Offre__c , (SELECT id , name , CriterionOffer__c, 
                                                             CriterionLabel__c ,
                                                             CriterionResponseAuthz__c  FROM ChildCriterionAuthorization__r) FROM asset WHERE id=:a.Id];
            
   			return newasset;
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            return null;
        }
        
    } 
    
    public class JSON2ApexCriterion {
        public String Id;
        public String Value;
    }
    public class JSON2ApexMoyen {
       	public Integer Key;
        public List<JSON2ApexCriterion> Criteres;
    }
        
    public class JSON2ApexEspace {
     	public Integer Key;
		public List<JSON2ApexCriterion> Criteres;
        public List<JSON2ApexMoyen> Moyens;
    }
    
    @AuraEnabled
    public static String getUserName() {
        return userinfo.getName();
    }
    
    @AuraEnabled 
    public static List<Offer__c> fetchUser(){ 

        User oUser = [SELECT id,Name,paramsWebMo__c  FROM User WHERE id =:userInfo.getUserId()];
      
        if(oUser.paramsWebMo__c !=null && String.isNotBlank(oUser.paramsWebMo__c) && String.isNotEmpty(oUser.paramsWebMo__c)){
            
            List<String> idOffer = new List<String>();
            
            for(String id : oUser.paramsWebMo__c.split('-'))
            {
                idOffer.add(id);
            }
            
            List<Offer__c> oOffer = [SELECT Id,Name FROM Offer__c WHERE TECH_id_webmo__c IN:idOffer];
            
            return (oOffer.size()>0) ? oOffer : null ;
            
        }else{
            return null;
        }
    }
    
    @AuraEnabled 
    public static void deleteParamWebMo(){
         User oUser = [SELECT id,Name,paramsWebMo__c  FROM User WHERE id =:userInfo.getUserId()];
         oUser.paramsWebMo__c = null;
        try {
            User u = new User();
            u.paramsWebMo__c = oUser.paramsWebMo__c;
            Update u;
        } catch (DmlException e) {
            system.debug('Erreur updating param');
        }  
    }

}