force-app/main/default/objects/Asset/fields/DiffusionPoint__c.field-meta.xml
<CustomField>
    <fullName>DiffusionPoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point de diffusion</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Autorisations</relationshipLabel>
    <relationshipName>ChildAutorisations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Offre__c.field-meta.xml
<CustomField>
    <fullName>Offre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Autorisations</relationshipLabel>
    <relationshipName>Actifs</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/BroadcastSpace__c/BroadcastSpace__c.object-meta.xml
<CustomObject>
    <label>Espace de diffusion</label>
    <nameField>
        <label>Nom de Espace de diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Espaces de diffusion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/BroadcastSpace__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Autorisation</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Espaces de diffusion</relationshipLabel>
    <relationshipName>ChildAuthorizationWayDiffusion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/Criterion__c/Criterion__c.object-meta.xml
<CustomObject>
    <label>Critère</label>
    <nameField>
        <label>Nom de Critère</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Critères</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/CriterionAuthorization__c.object-meta.xml
<CustomObject>
    <label>Critère d&#39;autorisation</label>
    <nameField>
        <displayFormat>AUTCR-{0000}</displayFormat>
        <label>Nom du critère d’autorisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères d&#39;autorisation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Autorisation</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionOffer__c.field-meta.xml
<CustomField>
    <fullName>CriterionOffer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Critère de l&#39;offre</label>
    <referenceTo>OfferCriterion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>Criterion_of_the_offer_child</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionResponseAuthz__c.field-meta.xml
<CustomField>
    <fullName>CriterionResponseAuthz__c</fullName>
    <label>Réponse de critère</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionToSendToOPA__c.field-meta.xml
<CustomField>
    <fullName>CriterionToSendToOPA__c</fullName>
    <formula>CriterionOffer__r.CriterionToSendToOPA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Critère à envoyer à OPA</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/WayDiffusion__c.field-meta.xml
<CustomField>
    <fullName>WayDiffusion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Moyen de Diffusion</label>
    <referenceTo>WayDiffusion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization2</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Nom de Offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Offer__c/fields/Scale__c.field-meta.xml
<CustomField>
    <fullName>Scale__c</fullName>
    <description>Code du Barème à utiliser pour calculer le montant de tarification</description>
    <inlineHelpText>Code du Barème à utiliser pour calculer le montant de tarification</inlineHelpText>
    <label>Barème</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WEB_RADIO_GEN_A</fullName>
                <label>1</label>
            </value>
            <value>
                <fullName>MAD_STR_GEN_A</fullName>
                <label>2</label>
            </value>
            <value>
                <fullName>SELDR_ABO_CAF_REST_PARISN_TG</fullName>
                <label>3</label>
            </value>
            <value>
                <fullName>SELDR_ABO_HOTEL_PART_COM_TG</fullName>
                <label>4</label>
            </value>
            <value>
                <fullName>SELOL_PORTAIL_CHEBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/OfferCriterion__c.object-meta.xml
<CustomObject>
    <label>Critère de l&#39;offre</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Numéro de Critère</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferCriterion__c/fields/criterion__c.field-meta.xml
<CustomField>
    <fullName>criterion__c</fullName>
    <label>Critère</label>
    <referenceTo>Criterion__c</referenceTo>
    <relationshipLabel>Critères de l&#39;offre</relationshipLabel>
    <relationshipName>ChildCriterion</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/CriterionToSendToOPA__c.field-meta.xml
<CustomField>
    <fullName>CriterionToSendToOPA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Critère à envoyer à OPA</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipName>Crit_res</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/OPACriterionName__c.field-meta.xml
<CustomField>
    <fullName>OPACriterionName__c</fullName>
    <externalId>true</externalId>
    <label>Nom du critère OPA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/OfferOutcome__c.object-meta.xml
<CustomObject>
    <label>Objectif de l&#39;offre</label>
    <nameField>
        <label>Nom de l&#39;objectif de l&#39;offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectifs de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferOutcome__c/fields/AssociatedRateName__c.field-meta.xml
<CustomField>
    <fullName>AssociatedRateName__c</fullName>
    <description>Nom du tarif associé 
(en l&#39;état, nom de l&#39;objectif pour objectif de type tarif, nom de l&#39;objectif sans _UTILE pour objectif de type répartition)</description>
    <label>Nom du tarif associé</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Objectifs de l&#39;offre</relationshipLabel>
    <relationshipName>ChildOfferOutcome</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/fields/OutcomeType__c.field-meta.xml
<CustomField>
    <fullName>OutcomeType__c</fullName>
    <description>Décrit le type de lignes remontées par l&#39;objectif</description>
    <label>Type d&#39;objectif</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OutcomeType</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/WayDiffusion__c/WayDiffusion__c.object-meta.xml
<CustomObject>
    <label>Moyen de Diffusion</label>
    <nameField>
        <label>Nom de Moyen de Diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moyens de Diffusion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Moyens de Diffusion</relationshipLabel>
    <relationshipName>ChildWayDiffusion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/WayDiffusion__c/fields/DiffusionPoint__c.field-meta.xml
<CustomField>
    <fullName>DiffusionPoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point de diffusion</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Moyens de diffusion</relationshipLabel>
    <relationshipName>ChildWayDiffusion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/globalValueSets/OutcomeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Rate</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Split</label>
    </customValue>
    <masterLabel>Type d&#39;objectifs</masterLabel>
</GlobalValueSet>

progressif/main/default/classes/OPADAO.cls
public without sharing class OPADAO {
// Classe DAO pour l'interface OPA

// Authorization Ids have to be set before use

    private static Set<Id> authorizationIds = new Set<Id>();

    

    public static void setAuthorizationId(Id id) {
        authorizationIds.add(id);
    }

    // Maps as readeable properties

    public static Map<Id, Asset> mapAuthorizations {
        get {
            if(mapAuthorizations == null) buildAuthorizationMap();
            return mapAuthorizations;
        }
        private set;
    }

    public static Map<Id, BroadcastSpace__c> mapSpaces {
        get {
            if(mapSpaces == null) buildSpacesMap();
            return mapSpaces;
        }
        private set;
    }

    public static Map<Id, WayDiffusion__c> mapWaysDiffusion {
        get {
            if(mapWaysDiffusion == null) buildWaysDiffusionMap();
            return mapWaysDiffusion;
        }
        private set;
    }

    public static Map<Id, Id> mapOfferIdByAuthorizationId {
        get {
            if(mapOfferIdByAuthorizationId == null) buildMapOfferIdByAuthorizationId();
            return mapOfferIdByAuthorizationId;
        }
        private set;
    }

    public static Map<Id, List<OfferOutcome__c>> mapLstOutcomesByOfferId {
        get {
            if(mapLstOutcomesByOfferId == null) buildOutcomeMaps();
            return mapLstOutcomesByOfferId;
        }
        private set;
    }

    public static Map<String, OfferOutcome__c> mapOutcomesByName {
        get {
            if(mapOutcomesByName == null) buildOutcomeMaps();
            return mapOutcomesByName;
        }
        private set;
    }

    public static Map<Id, List<CriterionAuthorization__c>> mapAuthorizationCriteriaByAuthorizationId {
        get {
            if(mapAuthorizationCriteriaByAuthorizationId == null) buildMapAuthorizationCriteriaByAuthorizationId();
            return mapAuthorizationCriteriaByAuthorizationId;
        }
        private set;
    }


// Map builders 

    private static void buildAuthorizationMap() {
        mapAuthorizations = new Map<Id, Asset>([
            SELECT Id, Name, Offre__c, Offre__r.Scale__c
            FROM Asset
            WHERE Id in :authorizationIds
        ]);
    }


    private static void buildSpacesMap() {        
        mapSpaces = new Map<Id, BroadcastSpace__c>([
            SELECT Id, Name
            FROM BroadcastSpace__c
            WHERE Authorization__c in :authorizationIds
        ]);
    }

    private static void buildWaysDiffusionMap() {
        mapWaysDiffusion = new Map<Id, WayDiffusion__c>([
            SELECT Id, BroadcastSpace__c, Name, DiffusionPoint__c
            FROM WayDiffusion__c
            WHERE BroadcastSpace__c in :mapSpaces.keySet()
        ]);
    } 

    private static void buildMapOfferIdByAuthorizationId() {
        mapOfferIdByAuthorizationId = new Map<Id, Id>();
        for(Asset autorisation : [
            SELECT Id, Name, Offre__c
            FROM Asset
            WHERE Id in :authorizationIds
        ]) {
            mapOfferIdByAuthorizationId.put(autorisation.Id, autorisation.Offre__c);
        }
    }

    private static void buildOutcomeMaps() {
    // Construction des maps mapLisOutcomesByOfferId et mapOutcomesByName
        mapLstOutcomesByOfferId = new Map<Id, List<OfferOutcome__c>>();
        mapOutcomesByName = new Map<String, OfferOutcome__c>();

        for(OfferOutcome__c outcome : [
            SELECT Id, Name, Offer__c, OutcomeType__c, AssociatedRateName__c, Company__c, RateType__c
            FROM OfferOutcome__c
            WHERE Offer__c in :mapOfferIdByAuthorizationId.values()
        ]) {
            if(!mapLstOutcomesByOfferId.containsKey(outcome.Offer__c)) {
                mapLstOutcomesByOfferId.put(outcome.Offer__c, new List<OfferOutcome__c>());
            }
            mapLstOutcomesByOfferId.get(outcome.Offer__c).add(outcome);

            mapOutcomesByName.put(outcome.Name, outcome);

        }
    }

    private static void buildMapAuthorizationCriteriaByAuthorizationId() {

        mapAuthorizationCriteriaByAuthorizationId = new Map<Id, List<CriterionAuthorization__c>>();
        for(CriterionAuthorization__c critere : [
            SELECT Authorization__c, CriterionResponseAuthz__c, CriterionOffer__r.OPACriterionName__c, CriterionOffer__r.criterion__r.TypeCriterion__c, BroadcastSpace__c, WayDiffusion__c
            FROM CriterionAuthorization__c
            WHERE Authorization__c in :authorizationIds AND CriterionToSendToOPA__c = true
            ORDER BY Id ASC NULLS FIRST
        ]) {
            if(!mapAuthorizationCriteriaByAuthorizationId.containsKey(critere.Authorization__c)) {
                mapAuthorizationCriteriaByAuthorizationId.put(critere.Authorization__c, new List<CriterionAuthorization__c>());
            }
            mapAuthorizationCriteriaByAuthorizationId.get(critere.Authorization__c).add(critere);
        }

    }

    





}