force-app/main/default/objects/Asset/fields/Offre__c.field-meta.xml
<CustomField>
    <fullName>Offre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Autorisations</relationshipLabel>
    <relationshipName>Actifs</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Nom de Offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Offer__c/fields/Scale__c.field-meta.xml
<CustomField>
    <fullName>Scale__c</fullName>
    <description>Code du Barème à utiliser pour calculer le montant de tarification</description>
    <inlineHelpText>Code du Barème à utiliser pour calculer le montant de tarification</inlineHelpText>
    <label>Barème</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WEB_RADIO_GEN_A</fullName>
                <label>1</label>
            </value>
            <value>
                <fullName>MAD_STR_GEN_A</fullName>
                <label>2</label>
            </value>
            <value>
                <fullName>SELDR_ABO_CAF_REST_PARISN_TG</fullName>
                <label>3</label>
            </value>
            <value>
                <fullName>SELDR_ABO_HOTEL_PART_COM_TG</fullName>
                <label>4</label>
            </value>
            <value>
                <fullName>SELOL_PORTAIL_CHEBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/classes/OPARequest.cls
public with sharing class OPARequest {
    public String bareme;
    public String body;
    //public Asset autorisation;

    private OPAResponse response;    
    
    // Constructeur
    public OPARequest(Id authorizationId) {
        OPADAO.setAuthorizationId(authorizationId);
        Asset autorisation = OPADAO.mapAuthorizations.get(authorizationId);
        bareme = autorisation.Offre__r.Scale__c;
        body = OPARequestBody.create(autorisation);
        //this.autorisation = autorisation;       
    }   

    public OPAResponse getRates() {
        HTTP http = new HTTP();
        HTTPRequest req = new HTTPRequest();
        req.setEndpoint('callout:callout_mario' + OPAConstants.SERVICE_URI + OPAConstants.VERSION + '/' + bareme);
        req.setMethod('POST');
        req.setHeader('Accept', 'application/json; charset=UTF-8');
        req.setHeader('Content-Type', 'application/json; charset=UTF-8');
        req.setHeader('SOAPAction', OPAConstants.SOAPACTION);
        req.setBody(body);
        System.debug('Body : ' + body);

        HttpResponse resp = http.send(req);

        if(resp.getStatusCode() == 200) {
            response = new OPAResponse(resp.getBody());
            response.OPARequestErrorCode = 0;
        } else {
            response = new OPAResponse();
            response.jsonResponse = resp.getBody();
            response.HTTPStatusCode = resp.getStatusCode();
            response.OPARequestErrorCode = -2000 -resp.getStatusCode();
        }
        return response;
        
    } 

}