force-app/main/default/objects/Asset/fields/Offre__c.field-meta.xml
<CustomField>
    <fullName>Offre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Autorisations</relationshipLabel>
    <relationshipName>Actifs</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/BroadcastSpace__c/BroadcastSpace__c.object-meta.xml
<CustomObject>
    <label>Espace de diffusion</label>
    <nameField>
        <label>Nom de Espace de diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Espaces de diffusion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/Criterion__c/Criterion__c.object-meta.xml
<CustomObject>
    <label>Critère</label>
    <nameField>
        <label>Nom de Critère</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Critères</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/CriterionAuthorization__c.object-meta.xml
<CustomObject>
    <label>Critère d&#39;autorisation</label>
    <nameField>
        <displayFormat>AUTCR-{0000}</displayFormat>
        <label>Nom du critère d’autorisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères d&#39;autorisation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionOffer__c.field-meta.xml
<CustomField>
    <fullName>CriterionOffer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Critère de l&#39;offre</label>
    <referenceTo>OfferCriterion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>Criterion_of_the_offer_child</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionResponseAuthz__c.field-meta.xml
<CustomField>
    <fullName>CriterionResponseAuthz__c</fullName>
    <label>Réponse de critère</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/WayDiffusion__c.field-meta.xml
<CustomField>
    <fullName>WayDiffusion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Moyen de Diffusion</label>
    <referenceTo>WayDiffusion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization2</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/OfferCriterion__c.object-meta.xml
<CustomObject>
    <label>Critère de l&#39;offre</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Numéro de Critère</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferCriterion__c/fields/criterion__c.field-meta.xml
<CustomField>
    <fullName>criterion__c</fullName>
    <label>Critère</label>
    <referenceTo>Criterion__c</referenceTo>
    <relationshipLabel>Critères de l&#39;offre</relationshipLabel>
    <relationshipName>ChildCriterion</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/OPACriterionName__c.field-meta.xml
<CustomField>
    <fullName>OPACriterionName__c</fullName>
    <externalId>true</externalId>
    <label>Nom du critère OPA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/OfferOutcome__c.object-meta.xml
<CustomObject>
    <label>Objectif de l&#39;offre</label>
    <nameField>
        <label>Nom de l&#39;objectif de l&#39;offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectifs de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/WayDiffusion__c.object-meta.xml
<CustomObject>
    <label>Moyen de Diffusion</label>
    <nameField>
        <label>Nom de Moyen de Diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moyens de Diffusion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Moyens de Diffusion</relationshipLabel>
    <relationshipName>ChildWayDiffusion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/classes/OPARequestBody.cls
public without sharing class OPARequestBody {

    public static String create(Id id) {
        Asset autorisation = OPADAO.mapAuthorizations.get(id);
        return create(autorisation); 
    }

    public static String create(Asset autorisation) { 
        String strBody = '';

        // Récupération des critères
        List<CriterionAuthorization__c> lstCriteres = OPADAO.mapAuthorizationCriteriaByAuthorizationId.get(autorisation.Id);
        if(lstCriteres == null) {
            throw new OPAService.OPAException('Pas de critères définis pour cette autorisation');
        }

        // Stockage des critères dans une permettant de les récupérer à partir des Id d'espace et de moyen (éventuellement à null pour les critères globaux ou juste liés à l'espace)
        Map<Id, Map<Id, List<CriterionAuthorization__c>>> mapEspaceMoyenToLstCritere = new Map<Id, Map<Id, List<CriterionAuthorization__c>>>();
        // Création du noeud "global" (null, null). Ainsi on est sur qu'il existe pour la suite (même s'il ne contient aps de critères)
        mapEspaceMoyenToLstCritere.put(null, new Map<Id, List<CriterionAuthorization__c>>());
        mapEspaceMoyenToLstCritere.get(null).put(null, new List<CriterionAuthorization__c>());
        // Création du noeud "global" (null, null) 
        for(CriterionAuthorization__c critAutorisation : lstCriteres) {
            Id moyenId = critAutorisation.WayDiffusion__c;
            Id espaceId = critAutorisation.BroadcastSpace__c;
            if(critAutorisation.WayDiffusion__c != null) {
                // A vérifier, n'est utile que si l'espâce n'est pas renseigné dans le cas d'un critère lié à un moyen
                espaceId = OPADAO.mapWaysDiffusion.get(moyenId).BroadcastSpace__c;
            }
            if(mapEspaceMoyenToLstCritere.get(espaceId) == null) {
                mapEspaceMoyenToLstCritere.put(espaceId, new Map<Id, List<CriterionAuthorization__c>>());
            }

            if(mapEspaceMoyenToLstCritere.get(espaceId).get(moyenId) == null) {
                mapEspaceMoyenToLstCritere.get(espaceId).put(moyenId, new List<CriterionAuthorization__c>());
            }

            mapEspaceMoyenToLstCritere.get(espaceId).get(moyenId).add(critAutorisation);
        }

        // Récupération des objectifs de l'offre
        List<OfferOutcome__c> lstObjectifs = OPADAO.mapLstOutcomesByOfferId.get(autorisation.Offre__c);
        if(lstObjectifs == null) {
            throw new OPAService.OPAException('Pas d\'objectifs définis pour l\'offre de cette autorisation');
        }

        // Création du document

        JSONGenerator gen = JSON.createGenerator(true);        

        // Début du body
        gen.writeStartObject(); // Body

        gen.writeFieldName('assess-request');
        gen.writeStartObject(); // assess-request


        // Génération des objectifs
        gen.writeFieldName('config');
        gen.writeStartObject(); // config
        // permet de récupérer le détail
        gen.writeBooleanField('show-properties', true);
        // liste des objectifs
        gen.writeFieldName('outcome');
        gen.writeStartObject(); // outcome
        gen.writeFieldName('entity');
        gen.writeStartObject(); // entity

        gen.writeStringField('@id', OPAConstants.ENTITY_TYPE_GLOBAL);
        gen.writeFieldName('attribute-outcome');
        gen.writeStartArray(); // attribute outcome
        for(OfferOutcome__c objectif : lstObjectifs) {
            gen.writeStartObject();
            gen.writeStringField('@id', objectif.Name);
            gen.writeStringField('@outcome-style', 'decision-report');
            gen.writeEndObject(); // attribute-outcome item
        }
        gen.writeEndArray(); // attribute-outcome
        gen.writeEndObject(); // entity
        gen.writeEndObject(); // outcome
        gen.writeEndObject(); // congig

        // Gestion des critères
        gen.writeFieldName('global-instance');
        gen.writeStartObject(); // global-instance

        gen.writeFieldName('attribute');
        gen.writeStartArray(); // attribute pour les critères globaux
        // Liste des critères 
        for(CriterionAuthorization__c critere:mapEspaceMoyenToLstCritere.get(null).get(null)) {
            writeCritere(gen, critere);
        }
        gen.writeEndArray(); // attribute pour les critères globaux
        // A voir, s'il y  a des moyens non ratachés à un espace . Dasn ce cas traiter ici le noeud mapEspaceMoyenToLstCritere.get(null) après avoir retiré
        // les critères du noeud

        mapEspaceMoyenToLstCritere.remove(null); // On ne garde plus que les critères liés à un espace

        if(mapEspaceMoyenToLstCritere.size() > 0) {
            gen.writeFieldName('entity'); 
            gen.writeStartObject(); // entityespaces
            gen.writeStringField('@id', OPAConstants.ENTITY_TYPE_SPACE);
            gen.writeFieldName('instance');
            gen.writeStartArray(); // instance espaces sono
            for(Id espaceId : mapEspaceMoyenToLstCritere.keyset()) {
                gen.writeStartObject(); // Objet espace sono
                gen.writeStringField('@id', espaceId);
                if(mapEspaceMoyenToLstCritere.get(espaceId).get(null).size() > 0) { // Il y a des critères au niveau de l'espace non liés à des moyens
                    gen.writeFieldName('attribute');
                    gen.writeStartArray(); // attributes espace de diff
                    for(CriterionAuthorization__c critere : mapEspaceMoyenToLstCritere.get(espaceId).get(null)) {
                        writeCritere(gen, critere);
                    }
                    gen.writeEndArray(); // attributes espace de diff
                    mapEspaceMoyenToLstCritere.get(espaceId).remove(null);
                }
                if(mapEspaceMoyenToLstCritere.get(espaceId).size() > 0) { // Il y a des critères sur les moyens de diffusion
                    gen.writeFieldName('entity');
                    gen.writeStartObject(); // entity moyens de l'espace de diff
                    gen.writeStringField('@id', OPAConstants.ENTITY_TYPE_WAY_DIFFUSION);
                    gen.writeFieldName('instance');
                    gen.WriteStartArray(); // instance moyens de l'espace de diff
                    for(Id moyenId : mapEspaceMoyenToLstCritere.get(espaceId).keySet()) {
                        gen.writeStartObject(); // Moyen de diff
                        gen.writeStringField('@id', moyenId);
                        gen.writeFieldName('attribute');
                        gen.writeStartArray(); // attributes moyen de diff
                        for(CriterionAuthorization__c critere : mapEspaceMoyenToLstCritere.get(espaceId).get(moyenId)) {
                            writeCritere(gen, critere);
                        }
                        gen.writeEndArray(); // attributes moyen de diff
                        gen.writeEndObject(); // Moyen de diff                        
                    }
                    gen.writeEndArray(); // instance moyens de l'espace de diff
                    gen.writeEndObject(); // entity moyens de l'espace de diff
                }
                gen.writeEndObject(); // Object espace sono
            }
            gen.writeEndArray(); // instance espaces sono
            gen.writeEndObject(); // entity espaces
        }

        gen.writeEndObject(); // global-instance

        // Fin de l'objet
        gen.writeEndObject(); // assess-request
        gen.writeEndObject(); // Body

        return gen.getAsString();

    }


    private static void writeCritere(JSONGenerator gen, CriterionAuthorization__c critere) {
    // Ecrit un objet critère d'autorisation dans la chaine json associée au générateur de la forme :
    // {"@id" : "nom_du_critere", "type_du_critere" : valeur_du_critere"}, la valeur_critere étant formatée
    // confiormément au type du critère
        String typeCritere = critere.CriterionOffer__r.criterion__r.TypeCriterion__c;
        String nomCritere = critere.CriterionOffer__r.OPACriterionName__c;
        String valeurCritere = critere.CriterionResponseAuthz__c;
        // Règle à valider. Si null, champ non envoyé
        if(valeurCritere != null){
            gen.writeStartObject(); // attribute item
            gen.writeStringField('@id', nomCritere);
            switch on typeCritere {
                when '3' { // Boolean
                    gen.writeBooleanField('boolean-val', valeurCritere == 'true');
                }
                when '5', '6' // Nombre, Devise
                {
                    gen.writeNumberField('number-val', Double.valueOf(valeurCritere));
                }
                when '4' // date
                {
                    gen.writeStringField('date-val', valeurCritere);
                }
                when else {
                    gen.writeStringField('text-val', valeurCritere);
                }
            }
            gen.writeEndObject(); // attribute item
        }
    }
}