progressif/main/default/objects/Account/fields/Activity_area__c.field-meta.xml
<CustomField>
    <fullName>Activity_area__c</fullName>
    <label>Secteur d&#39;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Secteurs_d_activites</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Asset/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contracts__c</referenceTo>
    <relationshipLabel>Autorisations</relationshipLabel>
    <relationshipName>Autorisations</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/Contracts__c/Contracts__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <displayFormat>20-{0000000000}</displayFormat>
        <label>N° Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Contracts__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nom du Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats</relationshipLabel>
    <relationshipName>Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/Criterion__c/Criterion__c.object-meta.xml
<CustomObject>
    <label>Critère</label>
    <nameField>
        <label>Nom de Critère</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Critères</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Criterion__c/fields/FormatCriterion__c.field-meta.xml
<CustomField>
    <fullName>FormatCriterion__c</fullName>
    <description>Format du champ pour ce critère. Exemple: Texte de 255, Nombre sur 10</description>
    <inlineHelpText>Format du champ pour ce critère. Exemple: Texte de 255, Nombre sur 10</inlineHelpText>
    <label>Format du critère</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/LabelCriterion__c.field-meta.xml
<CustomField>
    <fullName>LabelCriterion__c</fullName>
    <description>Libellé du critère affiché dans les écrans</description>
    <inlineHelpText>Libellé du critère affiché dans les écrans</inlineHelpText>
    <label>Libellé du critère</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/ListValues__c.field-meta.xml
<CustomField>
    <fullName>ListValues__c</fullName>
    <description>Les valeurs de la Picklist  , exemple (Val1,Val2,.....)</description>
    <inlineHelpText>Les valeurs de la Picklist ,exemple (Val1,Val2,.....)</inlineHelpText>
    <label>Liste des valeurs</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <label>Obligatoire</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Oui</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Cible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/TypeCriterion__c.field-meta.xml
<CustomField>
    <fullName>TypeCriterion__c</fullName>
    <description>Type de champ pour ce critère</description>
    <inlineHelpText>Type de champ pour ce critère</inlineHelpText>
    <label>Type du critère</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Nom de Offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Offer__c/fields/ActivityAreas__c.field-meta.xml
<CustomField>
    <fullName>ActivityAreas__c</fullName>
    <description>Permet de définir les secteurs d&#39;activités concernées par l&#39;offre. Une offre peut concernée plusieurs secteurs d&#39;activités</description>
    <inlineHelpText>Permet de définir les secteurs d&#39;activités concernées par l&#39;offre. Une offre peut concernée plusieurs secteurs d&#39;activités</inlineHelpText>
    <label>Secteur d&#39;activités</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Secteurs_d_activites</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <label>Vignette</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/TECH_QueryVisible__c.field-meta.xml
<CustomField>
    <fullName>TECH_QueryVisible__c</fullName>
    <description>Offres visibles uniquement pour le profil System Admin 

Ou Profil Client si l&#39;offre est coché Visible client

Ou profil chargé clientèle si l&#39;offre est coché visible Cdc</description>
    <formula>IF(       $Profile.Name=&#39;System Administrator&#39; 
					||   $Profile.Name=&#39;Administrateur système&#39;
					
					|| (CustomerProfiles__c &amp;&amp; ($Profile.Name=&#39;Customer Community Plus Login User&#39;|| $Profile.Name== &#39;Customer Community Plus Login User SACEM&#39;))
					|| (CdCOnlineProfiles__c &amp;&amp; ($Profile.Name=&#39;Chargé de clientèle réseau&#39;|| $Profile.Name== &#39;Chargé de clientèle online&#39;))
					
					, true, false
				
				
				
				
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visible requête</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/ValueOfferFamily__c.field-meta.xml
<CustomField>
    <fullName>ValueOfferFamily__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Famille d&#39;offre</label>
    <referenceTo>OfferFamily__c</referenceTo>
    <relationshipLabel>Offres</relationshipLabel>
    <relationshipName>ChildOffer</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/OfferCriterion__c.object-meta.xml
<CustomObject>
    <label>Critère de l&#39;offre</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Numéro de Critère</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferCriterion__c/fields/criterion__c.field-meta.xml
<CustomField>
    <fullName>criterion__c</fullName>
    <label>Critère</label>
    <referenceTo>Criterion__c</referenceTo>
    <relationshipLabel>Critères de l&#39;offre</relationshipLabel>
    <relationshipName>ChildCriterion</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/CriterionResponse__c.field-meta.xml
<CustomField>
    <fullName>CriterionResponse__c</fullName>
    <label>Réponse de critère</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/FormatCriterion__c.field-meta.xml
<CustomField>
    <fullName>FormatCriterion__c</fullName>
    <formula>criterion__r.FormatCriterion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Format du critère</label>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obligatoire</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Maxlength__c.field-meta.xml
<CustomField>
    <fullName>Maxlength__c</fullName>
    <label>Nbr de caractères maximal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageRangeOverFlow__c.field-meta.xml
<CustomField>
    <fullName>MessageRangeOverFlow__c</fullName>
    <label>Message erreur max</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageRangeUnderFlow__c.field-meta.xml
<CustomField>
    <fullName>MessageRangeUnderFlow__c</fullName>
    <label>Message d&#39;erreur min</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageValueMissing__c.field-meta.xml
<CustomField>
    <fullName>MessageValueMissing__c</fullName>
    <label>Message d&#39;erreur obligatoire</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageWhenTooLong__c.field-meta.xml
<CustomField>
    <fullName>MessageWhenTooLong__c</fullName>
    <label>Message erreur maxlength</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/MessageWhenTooShort__c.field-meta.xml
<CustomField>
    <fullName>MessageWhenTooShort__c</fullName>
    <label>Message erreur minlength</label>
    <type>TextArea</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Minimum__c.field-meta.xml
<CustomField>
    <fullName>Minimum__c</fullName>
    <label>Minimum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Minlength__c.field-meta.xml
<CustomField>
    <fullName>Minlength__c</fullName>
    <label>Nbr de caractères minimal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipName>Crit_res</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/OrderDisplay__c.field-meta.xml
<CustomField>
    <fullName>OrderDisplay__c</fullName>
    <inlineHelpText>Bonne pratique : saisissez comme ordre d&#39;affichage 10, 20 plutôt que 1, 2. Ainsi, vous pourrez insérer un critère plus tard sans devoir changer la numérotation !</inlineHelpText>
    <label>Ordre d&#39;affichage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Visible__c.field-meta.xml
<CustomField>
    <fullName>Visible__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/OfferFamily__c/OfferFamily__c.object-meta.xml
<CustomObject>
    <label>Famille d&#39;offre</label>
    <nameField>
        <label>Famille d&#39;offre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familles d&#39;offre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferFamily__c/fields/Detailsprices__c.field-meta.xml
<CustomField>
    <fullName>Detailsprices__c</fullName>
    <label>Details tarifs</label>
    <type>Url</type>
</CustomField>

progressif/main/default/objects/OfferFamily__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <formula>if(ISBLANK(  Url__c  ), &quot;&quot;, IMAGE(Url__c, &quot;Picture&quot;, 200, 200))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

progressif/main/default/globalValueSets/Secteurs_d_activites.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AEROPORT</fullName>
    </customValue>
    <customValue>
        <fullName>Agences événementielles</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPING</fullName>
    </customValue>
    <customValue>
        <fullName>CASINO</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>CINEMAS</fullName>
    </customValue>
    <customValue>
        <fullName>CIRQUES</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE DE DETAIL</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE DE DETAIL de DISQUES</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE GRANDE DISTRIBUTION</fullName>
    </customValue>
    <customValue>
        <fullName>EDITION &amp; COMMUNICATION</fullName>
    </customValue>
    <customValue>
        <fullName>EDS</fullName>
    </customValue>
    <customValue>
        <fullName>EDS / CABARET</fullName>
    </customValue>
    <customValue>
        <fullName>ENSEIGNEMENT</fullName>
    </customValue>
    <customValue>
        <fullName>ENTREPRISE &amp; ADMINISTRATION</fullName>
    </customValue>
    <customValue>
        <fullName>EQUIPEMENT SPORTIF</fullName>
    </customValue>
    <customValue>
        <fullName>ETABL CULTUREL</fullName>
    </customValue>
    <customValue>
        <fullName>ETABL SANTE</fullName>
    </customValue>
    <customValue>
        <fullName>EXPLOITANT PARKING</fullName>
    </customValue>
    <customValue>
        <fullName>HEBERGEMENT TOURISTIQUE</fullName>
    </customValue>
    <customValue>
        <fullName>Institutions sociales</fullName>
    </customValue>
    <customValue>
        <fullName>KARTING</fullName>
    </customValue>
    <customValue>
        <fullName>Organisateur événementiel occasionnel</fullName>
    </customValue>
    <customValue>
        <fullName>PARC d&#39;ATTRACTIONS ou de LOISIRS</fullName>
    </customValue>
    <customValue>
        <fullName>PRODUCTEUR de SPECTACLES</fullName>
    </customValue>
    <customValue>
        <fullName>PRODUCTEUR PHONO VIDEO</fullName>
    </customValue>
    <customValue>
        <fullName>SALLES de JEUX ARCADES</fullName>
    </customValue>
    <customValue>
        <fullName>SALON DE COIFFURE</fullName>
    </customValue>
    <masterLabel>Secteurs d&#39;activités</masterLabel>
</GlobalValueSet>

progressif/main/default/globalValueSets/Target.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Espace de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Moyen de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Point de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Autre</fullName>
        <isActive>false</isActive>
        <label>Autre</label>
    </customValue>
    <masterLabel>Cible</masterLabel>
</GlobalValueSet>

progressif/main/default/classes/LCCTR_OfferCtr.cls
public with sharing class LCCTR_OfferCtr {
    public LCCTR_OfferCtr() {

    }

        static Integer PAGE_SIZE = 9;

    public class Filters {
        public String searchKey { get;set; }
        public String[] categories { get;set; }
    }

    @AuraEnabled(Cacheable = true)
    public static List<OfferFamily__c>  findOfferFamily(id Recordid){
        try{
            // Gérer le filtre secteur d'activité From Contrat ou Utilisateur connecté
            string ActivityArea;
            string IdContract=String.valueof(Recordid);
            if ( Recordid!= null && IdContract.startsWithIgnoreCase('a0a')){
                Contracts__c ctc=[select id , AccountName__r.Activity_area__c from Contracts__c where id=:Recordid];
                ActivityArea=ctc.AccountName__r.Activity_area__c;
            } else {
                user usr =[select id, accountId from user where id=:UserInfo.getUserId() limit 1];
                if ( usr != null){ 
                    account acc=[select id , Activity_area__c from account where id=:usr.accountid limit 1];
                    ActivityArea=acc.Activity_area__c;
                }

            }
            
            List<OfferFamily__c> listOfferFamilyAll=new List <OfferFamily__c>();
            system.debug('rso activity area--'+ActivityArea);
            String query = 'SELECT Id,Name,Picture__c ,Url__c ,Detailsprices__c, description__c ,';
            query+='(select id , name  from childoffer__r  where TECH_QueryVisible__c=true ';
            
        

            //Filter secteur activity
            if ( String.isNotBlank(ActivityArea)){
            
            query+=' and ActivityAreas__c includes (:ActivityArea ) ';
            }
            query+=' ) FROM OfferFamily__c';
            system.debug('query--'+query);
        
                               
             listOfferFamilyAll = Database.query(query);

            // Get Url Ressource Static Url
             String url_file_ref= geturl_file_ref();                 
            
            List<OfferFamily__c> listOfferFamilyFiltred=new List <OfferFamily__c>();
            
            for ( OfferFamily__c family:listOfferFamilyAll ){
                
                if (family.childoffer__r.size()>0 ){
                    family.Url__c=url_file_ref+'/img/'+family.Url__c;
                    listOfferFamilyFiltred.add(family);
                }
            }
            system.debug('rso nb familly'+listOfferFamilyFiltred.size());
            return listOfferFamilyFiltred; 
            
        } 
        catch(Exception e) {
            
            System.debug('An exception occurred: ' + e.getMessage());
            return null;
        }   
    }

 @auraEnabled (Cacheable = true)
public static string geturl_file_ref (){
    StaticResource static_resource = [SELECT Id, SystemModStamp
                                            FROM StaticResource 
                                            WHERE Name = 'StyleCriterionComponent'
                                            LIMIT 1];
    String url_file_ref = '/resource/'
                                + String.valueOf(((DateTime)static_resource.get('SystemModStamp')).getTime())
                                + '/' 
                                + 'StyleCriterionComponent';
 return url_file_ref;                               
}

   

 @auraEnabled (Cacheable = true)
    public static List<OfferCriterion__c> getCriteres (Id RecordId){
        
        List<OfferCriterion__c> crits= new list <OfferCriterion__c>();
        
        crits = [SELECT Id, MessageRangeUnderFlow__c,MessageValueMissing__c , MessageRangeOverFlow__c ,CriterionResponse__c ,criterion__r.Name,criterion__r.Target__c, 
                 criterion__r.LabelCriterion__c , criterion__r.TypeCriterion__c ,FormatCriterion__c, 
                 criterion__r.ListValues__c, Mandatory__c,Offer__c , Maxlength__c,Minlength__c,Maximum__c , MessageWhenTooLong__c ,Minimum__c, MessageWhenTooShort__c ,
                 OrderDisplay__c, criterion__r.Section__c,criterion__r.PlaceHolder__c,criterion__r.DefaultValue__c,helpText__c,replaceLabel__c,Tech_LabelToDisplay__c,
                 messageWhenPatternMismatch__c,
                 (SELECT Id
                 FROM ChildSecondaryCriterionOfferCriterion__r )
                 FROM OfferCriterion__c 
                 WHERE Offer__c =:RecordId AND status__c='Principal' AND criterion__r.Target__c='Standard' AND Visible__c=true
              
                 ORDER BY  OrderDisplay__c ASC
                ];
        system.debug('rso crit size'+ crits.size());
        //Annule Groupement par section
       /* Map<string,List<OfferCriterion__c>> mapSectionCriteres = new Map <string,List<OfferCriterion__c>>();
       
        for ( OfferCriterion__c crit:crits){
            if ( mapSectionCriteres.containskey(crit.criterion__r.Section__c) ){
                system.debug('rso order'+crit.criterion__r.Section__c + crit.criterion__r.Name + crit.OrderDisplay__c);
                mapSectionCriteres.get(crit.criterion__r.Section__c).add(crit);
                system.debug('map'+mapSectionCriteres);
            }else {
                List<OfferCriterion__c> critssection=new list <OfferCriterion__c>();
                
                system.debug('rso order'+crit.criterion__r.Section__c + crit.criterion__r.Name + crit.OrderDisplay__c);
                critssection.add(crit);
                mapSectionCriteres.put(crit.criterion__r.Section__c,critssection);
                 system.debug('map'+mapSectionCriteres);
            }   
        }*/
             
        system.debug('RSO Inside apex'+crits);
        return crits;

    }
    

    @auraEnabled (Cacheable = true)
    public static List<OfferCriterion__c> getCriteressecondaires (Id RecordId , string Response){
       
        List<OfferCriterion__c> crits= new list <OfferCriterion__c>();
        
        crits = [SELECT Id,Name, criterion__r.Name, criterion__r.LabelCriterion__c , criterion__r.TypeCriterion__c , FormatCriterion__c, 
                 criterion__r.ListValues__c , Mandatory__c ,Offer__c , Maxlength__c ,Minlength__c ,Maximum__c ,MessageWhenTooLong__c,Minimum__c,MessageWhenTooShort__c, 
                 OrderDisplay__c , IfResponse__c , MessageRangeUnderFlow__c ,MessageValueMissing__c, MessageRangeOverFlow__c ,CriterionResponse__c,criterion__r.PlaceHolder__c,
                 criterion__r.DefaultValue__c,helpText__c,replaceLabel__c,Tech_LabelToDisplay__c, messageWhenPatternMismatch__c
                 
                 FROM OfferCriterion__c 
                 WHERE MainCriterion__c =:RecordId  AND IfResponse__c=:Response.trim() AND Visible__c=true
              
                 ORDER BY  OrderDisplay__c ASC
                ];
        return crits;

    }
    
    @auraEnabled (Cacheable = true)
    public static List<Offer__c> getOffersList(Id FamillyId, Id Recordid){
        system.debug('rso FamillyId'+FamillyId);
        
        // Gérer le filtre secteur d'activité From Contrat ou Utilisateur connecté
            string ActivityArea;
            string IdContract=String.valueof(Recordid);
            if ( Recordid!= null && IdContract.startsWithIgnoreCase('a0a')){
                Contracts__c ctc=[select id , AccountName__r.Activity_area__c from Contracts__c where id=:Recordid];
                ActivityArea=ctc.AccountName__r.Activity_area__c;
            } else {
                user usr =[select id, accountId from user where id=:UserInfo.getUserId() limit 1];
                if ( usr != null){ 
                    account acc=[select id , Activity_area__c from account where id=:usr.accountid limit 1];
                    ActivityArea=acc.Activity_area__c;
                }

            }

        List<Offer__c> OfferList = new List<Offer__c>();
         String query = 'SELECT Id, Name, Picture__c FROM Offer__c WHERE ValueOfferFamily__c=:FamillyId and TECH_QueryVisible__c=true ';

            if ( String.isNotBlank(ActivityArea) ){
                
            query+=' and ActivityAreas__c includes (:ActivityArea ) ';
            }
            query+=' ORDER BY createddate DESC';

            offerList = Database.query(query);

           // Get Url Ressource Static Url
            String url_file = geturl_file_ref();                 
            
            List<Offer__c> listOfferFiltred = new List <Offer__c>();
            
            for ( Offer__c offre:offerList ){
                
                    offre.Picture__c=url_file+'/img/'+offre.Picture__c;
                    listOfferFiltred.add(offre);
                
            }


        return listOfferFiltred;
    }

    // Save Autorisation + Criterion List
  @AuraEnabled 
    public static asset saveAutorisation(string RecordId , string Offer , string Criteres , string  Espaces){
        
        try {
            if(RecordId.countMatches('a0a')==0)    {
                
               Contracts__c  c  = new Contracts__c (); 
               c.AccountName__c = '0011w00000HxcAEAAZ';
               c.Status__c 	    ='En cours';
               c.ContractStartingDate__c = date.newInstance(2019, 10, 21);
               c.ClosingDate__c          = date.newInstance(2019, 11, 21);
                
               insert c;
               RecordId = c.Id; 
            }  
            
            //L'offre sélectionné
            Offer__c o = new Offer__c();
            o = [SELECT id , name FROM Offer__c WHERE id =:Offer LIMIT 1];
            
            //Le contract encours
            Contracts__c  c = new Contracts__c ();
            c = [SELECT id , AccountName__c  FROM Contracts__c  WHERE id=:RecordId LIMIT 1];
            
            //Créer Asset
            asset a        = new asset();
            a.Contracts__c = RecordId;
            a.AccountId    = c.AccountName__c ;
            a.Offre__c     = o.Id;
            a.Name		   = o.Name;
            
            system.debug ( 'insert a' + a);
            insert a;
            
            //Créer Critères autorisation Standard
            system.debug('CritListJson input : ' + Criteres);
            
            List <JSON2ApexCriterion> criteresparser=(List<JSON2ApexCriterion>)JSON.deserialize(Criteres,List<JSON2ApexCriterion>.class);
            List<CriterionAuthorization__c> CriterestoInsert = new List<CriterionAuthorization__c>();
            for (JSON2ApexCriterion crit:criteresparser ){
                //system.debug('test item crit '+crit.Id + 'val ' + crit.Value);
                CriterestoInsert.add( new CriterionAuthorization__c  (Authorization__c=a.id,CriterionOffer__c=crit.Id,CriterionResponseAuthz__c = crit.Value));
            }
                     
           
            //Créer Espaces 
            system.debug('EspacesJson input : ' + Espaces);
            
            List <JSON2ApexEspace> espacesparser=(List<JSON2ApexEspace>)JSON.deserialize(Espaces,List<JSON2ApexEspace>.class);
            
            //List <BroadcastSpace__c> EspacestoInsert = new List<BroadcastSpace__c>();
            for (JSON2ApexEspace Espace:espacesparser ){
                //system.debug('test item Espace '+Espace.Key);
                //EspacestoInsert.add ( new broadcast_space__c ( Autorisation__c=a.Id,Name= string.valueOf(Espace.Key)));
                BroadcastSpace__c  EspaceToinsert= new BroadcastSpace__c();
                EspaceToinsert.Authorization__c = a.Id;
                EspaceToinsert.Name=string.valueOf(Espace.Key);
                insert EspaceToinsert;
                
                for (JSON2ApexCriterion crit:Espace.Criteres ){
                 system.debug('Espace Crit'+crit) ;
                 CriterestoInsert.add( new CriterionAuthorization__c  (Authorization__c=a.id,CriterionOffer__c=crit.Id,
                                                                          CriterionResponseAuthz__c  = crit.Value,
																		  BroadcastSpace__c  = EspaceToinsert.Id
                                                                         ));
           
                }
                for (JSON2ApexMoyen moyen:Espace.Moyens ){
                    //system.debug('Espace Moyen'+moyen) ;
                    
                    WayDiffusion__c  MoyenToinsert  = new WayDiffusion__c();
                    MoyenToinsert.BroadcastSpace__c = EspaceToinsert.Id;
                    MoyenToinsert.Name=string.valueOf(moyen.Key);
                    //MoyenToinsert.Autorisation__c=a.Id;
                    
                    insert MoyenToinsert;
                    
                     for (JSON2ApexCriterion crit:moyen.Criteres ){
                     //system.debug('Moyen Crit'+crit) ;
                     CriterestoInsert.add( new CriterionAuthorization__c  (Authorization__c=a.id,CriterionOffer__c =crit.Id,
                                                                              CriterionResponseAuthz__c  = crit.Value,
                                                                              BroadcastSpace__c   = EspaceToinsert.Id,
                                                                              WayDiffusion__c  =MoyenToinsert.Id
                                                                             ));
           
                }
                    
                    
                }
                
                
             }
          
            
              //system.debug(CriterestoInsert.size());
             if (CriterestoInsert.size()>0 ){
                insert CriterestoInsert;
            }
            
            
            asset newasset = [SELECT id , name , Offre__c , (SELECT id , name , CriterionOffer__c, 
                                                             CriterionLabel__c ,
                                                             CriterionResponseAuthz__c  FROM ChildCriterionAuthorization__r) FROM asset WHERE id=:a.Id];
            
   			return newasset;
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            return null;
        }
        
    } 
    
    public class JSON2ApexCriterion {
        public String Id;
        public String Value;
    }
    public class JSON2ApexMoyen {
       	public Integer Key;
        public List<JSON2ApexCriterion> Criteres;
    }
        
    public class JSON2ApexEspace {
     	public Integer Key;
		public List<JSON2ApexCriterion> Criteres;
        public List<JSON2ApexMoyen> Moyens;
    }

}