progressif/main/default/objects/BroadcastSpace__c/BroadcastSpace__c.object-meta.xml
<CustomObject>
    <label>Espace de diffusion</label>
    <nameField>
        <label>Nom de Espace de diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Espaces de diffusion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/InvoicingLine__c/InvoicingLine__c.object-meta.xml
<CustomObject>
    <label>Ligne de répartition</label>
    <nameField>
        <label>Nom de la ligne de facturation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de répartition</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/InvoicingLine__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <label>Article</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/InvoicingLine__c/fields/DutyFreeAmount__c.field-meta.xml
<CustomField>
    <fullName>DutyFreeAmount__c</fullName>
    <label>Montant HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

progressif/main/default/objects/InvoicingLine__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Tarif</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipName>ChildInvoicingLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/InvoicingLine__c/fields/UseType__c.field-meta.xml
<CustomField>
    <fullName>UseType__c</fullName>
    <label>Type utile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/OfferOutcome__c.object-meta.xml
<CustomObject>
    <label>Objectif de l&#39;offre</label>
    <nameField>
        <label>Nom de l&#39;objectif de l&#39;offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectifs de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferOutcome__c/fields/AssociatedRateName__c.field-meta.xml
<CustomField>
    <fullName>AssociatedRateName__c</fullName>
    <description>Nom du tarif associé 
(en l&#39;état, nom de l&#39;objectif pour objectif de type tarif, nom de l&#39;objectif sans _UTILE pour objectif de type répartition)</description>
    <label>Nom du tarif associé</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/fields/OutcomeType__c.field-meta.xml
<CustomField>
    <fullName>OutcomeType__c</fullName>
    <description>Décrit le type de lignes remontées par l&#39;objectif</description>
    <label>Type d&#39;objectif</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OutcomeType</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>Tarif</label>
    <nameField>
        <label>Nom du tarif</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tarifs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/Rate__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Autorisation</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Tarifs</relationshipLabel>
    <relationshipName>ChildRate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/Rate__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Société</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Rate__c/fields/DutyFreeRealAmount__c.field-meta.xml
<CustomField>
    <fullName>DutyFreeRealAmount__c</fullName>
    <label>Montant HT réel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

progressif/main/default/objects/Rate__c/fields/DutyFreeTheoreticalAmount__c.field-meta.xml
<CustomField>
    <fullName>DutyFreeTheoreticalAmount__c</fullName>
    <label>Montant HT théorique</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

progressif/main/default/objects/Rate__c/fields/RateType__c.field-meta.xml
<CustomField>
    <fullName>RateType__c</fullName>
    <label>Type de tarif</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RateType</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/RateLine__c/RateLine__c.object-meta.xml
<CustomObject>
    <label>Ligne de tarif</label>
    <nameField>
        <label>Nom de la ligne de tarif</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de tarif</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/RateLine__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Lignes de tarif</relationshipLabel>
    <relationshipName>ChildRateLine</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/RateLine__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Libellé</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/RateLine__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Niveau d&#39;indentation de la ligne de facturation.
Les lignes de niveau 0 ou dont le niveau n&#39;est pas renseigné ne sont pas indentées</description>
    <label>NiveauIndentation</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/RateLine__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <inlineHelpText>Bonne pratique : saisissez comme ordre d&#39;affichage 10, 20 plutôt que 1, 2.</inlineHelpText>
    <label>Rang</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/RateLine__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Tarif</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Lignes de tarif</relationshipLabel>
    <relationshipName>ChildRateLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/globalValueSets/Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SACEM</fullName>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>SPRE</fullName>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>SDRM</fullName>
        <label>3</label>
    </customValue>
    <masterLabel>Société</masterLabel>
</GlobalValueSet>

progressif/main/default/globalValueSets/OutcomeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Rate</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Split</label>
    </customValue>
    <masterLabel>Type d&#39;objectifs</masterLabel>
</GlobalValueSet>

progressif/main/default/globalValueSets/RateType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tarif general</fullName>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>Tarif reduit</fullName>
        <label>2</label>
    </customValue>
    <masterLabel>Type de tarif</masterLabel>
</GlobalValueSet>

progressif/main/default/classes/OPAResponse.cls
public without sharing class OPAResponse {

    private static Integer INITIAL_LEVEL = 0; 
    // Niveau d'indentation des lignes de plus haut niveau

    // Attributes
    public Map<String, RateData> rates;
    public Integer HTTPStatusCode;
    public String jsonResponse;
    public Integer OPARequestErrorCode;


    // Constructors
    public OPAResponse() {
        rates = new Map<String, RateData>();
    }

    public OPAResponse(String jsonResponse) {

        System.debug('///// REPONSE ///');
        System.Debug(JSON.serializePretty(JSON.deserializeUntyped(jsonResponse)));   
        System.debug('/// FIN REPONSE ///');
        rates = new Map<String, RateData>();
        Integer ratesCreated = createRateData(jsonResponse);
       
        System.debug(ratesCreated);
    }

    // Public Method

    // Ecritures des données de lignes dans les sObjects correspondants: Tarifs (Rate__c), lignes de Tarif (RateLine__c) 
    // et lignes de répartition (BillingLine__c)
    public void writeRatesToAuthorization(Id authorizationId) {
        Map<String, Rate__c> mapRates = new Map<String, Rate__c>();
        List<RateLine__c> lstRateLines = new List<RateLine__c>();
        List<InvoicingLine__c> lstInvoicingLines = new List<InvoicingLine__c>();

        Map<String, OfferOutcome__c> OutcomeProperties = OPADAO.mapOutcomesByName;
        System.debug(OutcomeProperties);
        Map<Id, BroadcastSpace__c> mapSpaces = OPADAO.mapSpaces;

        //  Ecriture en base des objets tarif
        System.debug(outcomeProperties.keyset());
        for(RateData rate : rates.values()) {
            system.debug('Rate name : ' + rate.name);
            system.debug('Corresponding putcome : ' + OutcomeProperties.get(rate.Name));
            mapRates.put(rate.Name, new Rate__c(
                Name = rate.Name,
                CurrencyIsoCode = 'EUR',
                Company__c = OutcomeProperties.get(rate.Name).Company__c,
                RateType__c = OutcomeProperties.get(rate.Name).RateType__c,
                DutyFreeTheoreticalAmount__c = rate.ValueHT,
                DutyFreeRealAmount__c = rate.ValueHT,
                Asset__c = authorizationId
            ));
            if(OutcomeProperties.get(rate.Name).Company__c == 'SPRE') {
                // TODO : compute real amout for SPRE
                // lstRates.get(rate.Name).DutyFreeRealAmount__c = computeSpreRealAmount(rate.ValueHT);
            }
        }
        insert mapRates.values();


        // Ecriture en base des lignes de tarif et des lignes de répartition
        for(RateData rate : rates.values()) {
            Integer rank = 1;
            for(RateLineData rateLine : rate.RateLines) {
                lstRateLines.add(new RateLine__c(
                    Name = rateLine.Name,
                    Description__c = rateLine.Label,
                    CurrencyIsoCode = 'EUR',
                    Rank__c = rank++,
                    Rate__c = mapRates.get(rate.Name).Id,
                    Level__c = rateLine.Level,
                    DutyFreeAmount__c = rateLine.ValueHT,
                    BroadcastSpace__c = rateLine.entityId==OPAConstants.ENTITY_TYPE_SPACE?rateLine.instanceId:null
                ));
            }

            for(BillingLineData billingLine : rate.BillingLines) {
                lstInvoicingLines.add(new InvoicingLine__c(
                    Name = billingLine.Name,
                    Rate__c = mapRates.get(rate.Name).Id,
                    UseType__c = billingLine.TypeUtile,
                    Article__c = billingLine.Article,
                    DutyFreeAmount__c = billingLine.ValueHT,
                    CurrencyIsoCode = 'EUR'
                ));
            }
        }
        if(lstRateLines.size() > 0) {
            insert lstRateLines;
        }
        if(lstInvoicingLines.size() > 0)  {
            insert lstInvoicingLines;
        }

    }

    // Subclasses
    public class RateData {
        public String Name;
        public Double ValueHT;
        public List<RateLineData> RateLines;
        public List<BillingLineData> BillingLines;

        public RateData() {
            RateLines = new List<RateLineData>();
            BillingLines = new List<BillingLineData>();
        }
    }
    
    public class RateLineData {
        public String Name;
        public String Label;
        public Double ValueHT;
        public Integer Level;
        public String EntityId;
        public String InstanceId;
    }

    public class BillingLineData {
        public String Name;
        public String Label;
        public Double ValueHT;
        public String TypeUtile;
        public String Article;
    }


    // Private methods
    private Integer createRateData(String jsonResponse) {
        System.debug('OPA response : ' + jsonResponse);

        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        Map<String, Object> assessResponse = (Map<String, Object>)responseMap.get('assess-response');
        Map<String, Object> globalInstance = (Map<String, Object>)assessResponse.get('global-instance');
        List<Object> attributes = (List<Object>)globalInstance.get('attribute');

        Rates.clear();

        for(Object item:attributes) {
            Map<String, Object> attribute = (Map<String, Object>)item;
            if((String)attribute.get('@inferred') == 'true') {
                String rateName = getRateName(attribute);
                if(!rates.containsKey(rateName)) {
                    rates.put(rateName, new RateData());
                }
                RateData rate = rates.get(rateName);
                rate.Name = rateName;
                rate.ValueHT = (Double)attribute.get('number-val');
                Map<String, Object> decisionReport = (Map<String,Object>)attribute.get('decision-report');

                if(containsRateLines(attribute)) {
                    rate.RateLines = createRateLineData(decisionReport);
                } else {
                    rate.BillingLines = createBillingLineData(decisionReport);
                }
            }
        }
        return rates.size();
    }

    private Boolean containsRateLines(Map<String, Object> attribute) {
        // returns true if rate describes rate lines, false if it describes billing lines
        String rateName = (String)attribute.get('@id');
        return OPADAO.mapOutcomesByName.get(rateName).OutcomeType__c == OPAConstants.OUTCOME_TARIF;
    }

    private String getRateName(Map<String, Object> attribute) {
        System.debug(attribute);
        String rateName = (String)attribute.get('@id');
        return OPADAO.mapOutcomesByName.get(rateName).AssociatedRateName__c;
    }
    
    // Lecture des lignes de tarif 

    private List<RateLineData> createRateLineData(Map<String, Object> decisionReport) {
        List<Map<String, Object>> attributeNodes = getAttributeNodes(decisionReport);
        List<RateLineData> rateLines = readAttributeNodeList(attributeNodes, INITIAL_LEVEL);
        return rateLines;       
    }


    private List<Map<String, Object>> getAttributeNodes(Map<String, Object> parentAttributeNode) {
        // récupère une liste d'attrinute-nodes. Convertit l'objet isolé en liste si nécessaire
        List<Map<String,Object>> attributeNodes;
        if(parentAttributeNode.get('attribute-node') == null) {
            // Il n'y a pas de sous noeud ==> Retour null
            attributeNodes = null;
        } else if(parentAttributeNode.get('attribute-node') instanceof List<Object>) {
            // Le sous noeud est une liste de noeuds ==> On récupère ditrectement la liste
            attributeNodes = new List<Map<String,Object>>();
            for(Object obj : (List<Object>)parentAttributeNode.get('attribute-node')) {
                attributeNodes.add((Map<String,Object>)obj);
            }
        } else {
            // Le sous noeud est un objet isolé ==> On l'ajoute à une liste vide
            attributeNodes = new List<Map<String,Object>>();
            attributeNodes.add((Map<String,Object>)parentAttributeNode.get('attribute-node'));
        }
        return attributeNodes;
    }

    private List<RateLineData> readAttributeNodeList(List<Map<String, Object>> attributeNodes, Integer level) {
    // Méthode récursive de lecture des noeuds d'attibuts
    // Ecrit les attibuts du noeud en cours, et, si ce dernier contient un autre noeud d'attributs, 
    // est rappelée récursivement pour l'écriture de cet autre noeud avec un niveau incrémenté de 1.
        List<RateLineData> lstRateLines = new List<RateLineData>();
        for(Map<String, Object> attributeNode : attributeNodes) {
            RateLineData rateLine = new RateLineData();
            rateLine.Name = (String)attributeNode.get('@attribute-id');
            if((String)attributeNode.get('@type') == 'currency') {
                // On ne récupère la valeur numéroqie que pour les lignes associées à des montants (type = currency)
                rateLine.ValueHT = (Double)attributeNode.get('number-val');
            }
            rateLine.Label = (String)attributeNode.get('@text');
            rateLine.EntityId = (String)attributeNode.get('@entity-id');
            rateLine.InstanceId = (String)attributeNode.get('@instance-id');
            rateLine.Level = level;
            lstRateLines.add(rateLine);
            List<Map<String, Object>> childNodes = getAttributeNodes(attributeNode);
            if(childNodes <> null) {
                lstRateLines.addAll(readAttributeNodeList(childNodes, level +1));
            }
        }
        return lstRateLines;
    }

    // Lecture des lignes de répartition
    private List<BillingLineData> createBillingLineData(Map<String, Object> decisionReport) {
        List<BillingLineData> billingLines = new List<BillingLineData>();
        BillingLineData billingLine;
        // Niveau 1 : total
        Map<String, Object> attributeNode = (Map<String,Object>)decisionReport.get('attribute-node');
        String rateLineDataName = (String)attributeNode.get('@attribute-id');
        // Niveau 2 : codes utiles
        List<Map<String,Object>> typeUtileNodes = getAttributeNodes(attributeNode);
        for(Map<String, Object> typeUtileNode : typeUtileNodes) {
            String typeUtile = (String)typeUtileNode.get('@attribute-id');
            // Niveau 3 : articles
            List<Map<String,Object>> articleNodes = getAttributeNodes(typeUtileNode);

            for(Map<String, Object> articleNode : articleNodes) {
                billingLine = new BillingLineData();
                billingLine.Label = (String)articleNode.get('@text');
                billingLine.Name = rateLineDataName;
                billingLine.TypeUtile = typeUtile;
                billingLine.Article = (String)articleNode.get('@attribute-id');
                billingLine.ValueHT = (Double)articleNode.get('number-val');
                billingLines.add(billingLine);
            }           
        }

        return billingLines;
    }



}