progressif/main/default/objects/BroadcastSpace__c/BroadcastSpace__c.object-meta.xml
<CustomObject>
    <label>Espace de diffusion</label>
    <nameField>
        <label>Nom de Espace de diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Espaces de diffusion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/BroadcastSpace__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Autorisation</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Espaces de diffusion</relationshipLabel>
    <relationshipName>ChildAuthorizationWayDiffusion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/Criterion__c/Criterion__c.object-meta.xml
<CustomObject>
    <label>Critère</label>
    <nameField>
        <label>Nom de Critère</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Critères</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Criterion__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <label>Ordre d&#39;affichage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/LabelCriterion__c.field-meta.xml
<CustomField>
    <fullName>LabelCriterion__c</fullName>
    <description>Libellé du critère affiché dans les écrans</description>
    <inlineHelpText>Libellé du critère affiché dans les écrans</inlineHelpText>
    <label>Libellé du critère</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <label>Obligatoire</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Oui</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <description>Nom de la section dans laquelle affichée le critère sur la page de saisie de l&#39;autorisation</description>
    <inlineHelpText>Nom de la section dans laquelle affichée le critère sur la page de saisie de l&#39;autorisation</inlineHelpText>
    <label>Section</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Cible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Target</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Criterion__c/fields/TypeCriterion__c.field-meta.xml
<CustomField>
    <fullName>TypeCriterion__c</fullName>
    <description>Type de champ pour ce critère</description>
    <inlineHelpText>Type de champ pour ce critère</inlineHelpText>
    <label>Type du critère</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/CriterionAuthorization__c.object-meta.xml
<CustomObject>
    <label>Critère d&#39;autorisation</label>
    <nameField>
        <displayFormat>AUTCR-{0000}</displayFormat>
        <label>Nom du critère d’autorisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères d&#39;autorisation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Autorisation</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/WayDiffusion__c.field-meta.xml
<CustomField>
    <fullName>WayDiffusion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Moyen de Diffusion</label>
    <referenceTo>WayDiffusion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization2</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Nom de Offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/Offer__c/fields/ActivityAreas__c.field-meta.xml
<CustomField>
    <fullName>ActivityAreas__c</fullName>
    <description>Permet de définir les secteurs d&#39;activités concernées par l&#39;offre. Une offre peut concernée plusieurs secteurs d&#39;activités</description>
    <inlineHelpText>Permet de définir les secteurs d&#39;activités concernées par l&#39;offre. Une offre peut concernée plusieurs secteurs d&#39;activités</inlineHelpText>
    <label>Secteur d&#39;activités</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Secteurs_d_activites</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/fields/CollectionFamily__c.field-meta.xml
<CustomField>
    <fullName>CollectionFamily__c</fullName>
    <description>Famille qui peut vendre l&#39;offre</description>
    <label>Famille de collecte</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Droits Généraux</fullName>
                <label>1</label>
            </value>
            <value>
                <fullName>Grands comptes - Nationaux</fullName>
                <label>2</label>
            </value>
            <value>
                <fullName>Grands comptes - Cinéma</fullName>
                <label>3</label>
            </value>
            <value>
                <fullName>Grands comptes - Spectacles</fullName>
                <label>4</label>
            </value>
            <value>
                <fullName>Licences Online</fullName>
                <label>5</label>
            </value>
            <value>
                <fullName>Licences Phono</fullName>
                <label>6</label>
            </value>
            <value>
                <fullName>Licences Média audiovisuels</fullName>
                <label>7</label>
            </value>
            <value>
                <fullName>Tous</fullName>
                <label>8</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/fields/PeriodicityOffer__c.field-meta.xml
<CustomField>
    <fullName>PeriodicityOffer__c</fullName>
    <description>Permet de définir la périodicité de l&#39;offre</description>
    <inlineHelpText>Permet de définir la périodicité de l&#39;offre</inlineHelpText>
    <label>Périodicité de l&#39;offre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abonnement d&#39;un an renouvelable</fullName>
                <label>1</label>
            </value>
            <value>
                <fullName>Abonnement non renouvelable</fullName>
                <label>2</label>
            </value>
            <value>
                <fullName>Evénement occasionnel</fullName>
                <label>3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/Offer__c/fields/StartingDateValidity__c.field-meta.xml
<CustomField>
    <fullName>StartingDateValidity__c</fullName>
    <description>Date de début de validité de l&#39;offre</description>
    <label>Date de début de validité</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

progressif/main/default/objects/Offer__c/fields/TypeProcess__c.field-meta.xml
<CustomField>
    <fullName>TypeProcess__c</fullName>
    <label>Type de parcours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parcours complet</fullName>
                <label>1</label>
            </value>
            <value>
                <fullName>Prospection</fullName>
                <label>2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/OfferCriterion__c.object-meta.xml
<CustomObject>
    <label>Critère de l&#39;offre</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Numéro de Critère</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferCriterion__c/fields/criterion__c.field-meta.xml
<CustomField>
    <fullName>criterion__c</fullName>
    <label>Critère</label>
    <referenceTo>Criterion__c</referenceTo>
    <relationshipLabel>Critères de l&#39;offre</relationshipLabel>
    <relationshipName>ChildCriterion</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obligatoire</label>
    <type>Checkbox</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipName>Crit_res</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/OfferOutcome__c.object-meta.xml
<CustomObject>
    <label>Objectif de l&#39;offre</label>
    <nameField>
        <label>Nom de l&#39;objectif de l&#39;offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectifs de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/OfferOutcome__c/fields/AssociatedRateName__c.field-meta.xml
<CustomField>
    <fullName>AssociatedRateName__c</fullName>
    <description>Nom du tarif associé 
(en l&#39;état, nom de l&#39;objectif pour objectif de type tarif, nom de l&#39;objectif sans _UTILE pour objectif de type répartition)</description>
    <label>Nom du tarif associé</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offre</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Objectifs de l&#39;offre</relationshipLabel>
    <relationshipName>ChildOfferOutcome</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/fields/OutcomeType__c.field-meta.xml
<CustomField>
    <fullName>OutcomeType__c</fullName>
    <description>Décrit le type de lignes remontées par l&#39;objectif</description>
    <label>Type d&#39;objectif</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OutcomeType</valueSetName>
    </valueSet>
</CustomField>

progressif/main/default/objects/WayDiffusion__c/WayDiffusion__c.object-meta.xml
<CustomObject>
    <label>Moyen de Diffusion</label>
    <nameField>
        <label>Nom de Moyen de Diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moyens de Diffusion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Moyens de Diffusion</relationshipLabel>
    <relationshipName>ChildWayDiffusion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/globalValueSets/OutcomeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Rate</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Split</label>
    </customValue>
    <masterLabel>Type d&#39;objectifs</masterLabel>
</GlobalValueSet>

progressif/main/default/globalValueSets/Secteurs_d_activites.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AEROPORT</fullName>
    </customValue>
    <customValue>
        <fullName>Agences événementielles</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BOWLING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPING</fullName>
    </customValue>
    <customValue>
        <fullName>CASINO</fullName>
    </customValue>
    <customValue>
        <fullName>CHR</fullName>
    </customValue>
    <customValue>
        <fullName>CINEMAS</fullName>
    </customValue>
    <customValue>
        <fullName>CIRQUES</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE DE DETAIL</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE DE DETAIL de DISQUES</fullName>
    </customValue>
    <customValue>
        <fullName>COMMERCE GRANDE DISTRIBUTION</fullName>
    </customValue>
    <customValue>
        <fullName>EDITION &amp; COMMUNICATION</fullName>
    </customValue>
    <customValue>
        <fullName>EDS</fullName>
    </customValue>
    <customValue>
        <fullName>EDS / CABARET</fullName>
    </customValue>
    <customValue>
        <fullName>ENSEIGNEMENT</fullName>
    </customValue>
    <customValue>
        <fullName>ENTREPRISE &amp; ADMINISTRATION</fullName>
    </customValue>
    <customValue>
        <fullName>EQUIPEMENT SPORTIF</fullName>
    </customValue>
    <customValue>
        <fullName>ETABL CULTUREL</fullName>
    </customValue>
    <customValue>
        <fullName>ETABL SANTE</fullName>
    </customValue>
    <customValue>
        <fullName>EXPLOITANT PARKING</fullName>
    </customValue>
    <customValue>
        <fullName>HEBERGEMENT TOURISTIQUE</fullName>
    </customValue>
    <customValue>
        <fullName>Institutions sociales</fullName>
    </customValue>
    <customValue>
        <fullName>KARTING</fullName>
    </customValue>
    <customValue>
        <fullName>Organisateur événementiel occasionnel</fullName>
    </customValue>
    <customValue>
        <fullName>PARC d&#39;ATTRACTIONS ou de LOISIRS</fullName>
    </customValue>
    <customValue>
        <fullName>PRODUCTEUR de SPECTACLES</fullName>
    </customValue>
    <customValue>
        <fullName>PRODUCTEUR PHONO VIDEO</fullName>
    </customValue>
    <customValue>
        <fullName>SALLES de JEUX ARCADES</fullName>
    </customValue>
    <customValue>
        <fullName>SALON DE COIFFURE</fullName>
    </customValue>
    <masterLabel>Secteurs d&#39;activités</masterLabel>
</GlobalValueSet>

progressif/main/default/globalValueSets/Target.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Espace de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Moyen de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Point de diffusion</fullName>
    </customValue>
    <customValue>
        <fullName>Autre</fullName>
        <isActive>false</isActive>
        <label>Autre</label>
    </customValue>
    <masterLabel>Cible</masterLabel>
</GlobalValueSet>

progressif/main/default/classes/OPADataFactory.cls
@IsTest
public with sharing class OPADataFactory {



    private static List<Criterion__c> createCriteria() {
        List<Criterion__c> lstCriteres = new List<Criterion__c>();
        Criterion__c critere;
        // Critère numérique
        critere = new Criterion__c(
            Name = 'Critère numérique',
            Target__c = 'Standard',
            TypeCriterion__c = OPAConstants.TYPE_NOMBRE,
            LabelCriterion__c = 'Nombre',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 10);
        lstCriteres.add(critere);
        // Critère Booléen
        critere = new Criterion__c(
            Name = 'Critère booleen',
            Target__c = 'Standard',
            TypeCriterion__c = OPAConstants.TYPE_BOOLEEN,
            LabelCriterion__c = 'Booleen',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 20);
        lstCriteres.add(critere);
        // Critère chaîne
        critere = new Criterion__c(
            Name = 'Critère texte',
            Target__c = 'Standard',
            TypeCriterion__c = OPAConstants.TYPE_TEXTE,
            LabelCriterion__c = 'Texte',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 30);
        lstCriteres.add(critere);
        critere = new Criterion__c(
            Name = 'Critère date',
            Target__c = 'Standard',
            TypeCriterion__c = OPAConstants.TYPE_DATE,
            LabelCriterion__c = 'Date',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 40);
        lstCriteres.add(critere);  
        insert lstCriteres; 
        return lstCriteres;     
    }

    private static List<Criterion__c> createSpaceCriteria() {
        List<Criterion__c> lstCriteres = new List<Criterion__c>();
        Criterion__c critere;
        // Critère numérique
        critere = new Criterion__c(
            Name = 'Espace numérique',
            Target__c = OPAConstants.TARGET_SPACE,
            TypeCriterion__c = OPAConstants.TYPE_NOMBRE,
            LabelCriterion__c = 'Espace Nombre',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 10);
        lstCriteres.add(critere);
        // Critère chaîne
        critere = new Criterion__c(
            Name = 'Espace texte',
            Target__c = OPAConstants.TARGET_SPACE,
            TypeCriterion__c = OPAConstants.TYPE_TEXTE,
            LabelCriterion__c = 'Espace Texte',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 30);
        lstCriteres.add(critere);
        insert lstCriteres; 
        return lstCriteres;     
    }

    private static List<Criterion__c> createMoyenCriteria() {
        List<Criterion__c> lstCriteres = new List<Criterion__c>();
        Criterion__c critere;
        // Critère numérique
        critere = new Criterion__c(
            Name = 'Moyen numérique',
            Target__c = OPAConstants.TARGET_MOYEN,
            TypeCriterion__c = OPAConstants.TYPE_NOMBRE,
            LabelCriterion__c = 'Moyen Nombre',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 10);
        lstCriteres.add(critere);
        // Critère chaîne
        critere = new Criterion__c(
            Name = 'Moyen texte',
            Target__c = OPAConstants.TARGET_MOYEN,
            TypeCriterion__c = OPAConstants.TYPE_TEXTE,
            LabelCriterion__c = 'Moyen Texte',
            Section__c = 'Test',
            Mandatory__c = OPAConstants.BOOLEAN_NO,
            DisplayOrder__c = 30);
        lstCriteres.add(critere);
        insert lstCriteres; 
        return lstCriteres;     
    }


    private static List<BroadcastSpace__c> createEspaces(Asset autorisation) {
        List<BroadcastSpace__c> lstEspaces = new List<BroadcastSpace__c>();
        for(Integer i = 1;i<=3;i++) {
            lstEspaces.add(new BroadcastSpace__c(
                Name = 'ESPACE_' + i,
                Authorization__c = autorisation.Id
            ));
        }

        insert lstEspaces;
        return lstEspaces;
    }

    private static List<WayDiffusion__c> createMoyensDiffusion(List<BroadcastSpace__c> lstEspaces) {
        List<WayDiffusion__c> lstMoyens = new List<WayDiffusion__c>();
        for(BroadcastSpace__c espace : lstEspaces) {
            for(Integer i = 1;i<=3;i++) {
                lstMoyens.Add(new WayDiffusion__c(
                    Name = 'MOYEN_' + espace.Name.right(1) + '_' + i,
                    BroadcastSpace__c = espace.Id
                ));
            }          
        }
        insert lstMoyens;
        return lstMoyens;
    }

    private static List<OfferOutcome__c> createObjectifs(Offer__c offer) {
        List<OfferOutcome__c> lstObjectifs = new List<OfferOutcome__c>();
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_REDEV_SACEM_THEO_TG_GLOBAL',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SACEM,
            RateType__c = OPAConstants.TARIF_GENERAL,
            OutcomeType__c = OPAConstants.OUTCOME_TARIF,
            AssociatedRateName__c = 'NUM_REDEV_SACEM_THEO_TG_GLOBAL'
        ));
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_REDEV_SACEM_THEO_TR_GLOBAL',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SACEM,
            RateType__c = OPAConstants.TARIF_REDUIT,
            OutcomeType__c = OPAConstants.OUTCOME_TARIF,
            AssociatedRateName__c = 'NUM_REDEV_SACEM_THEO_TR_GLOBAL'
        ));
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_REDEV_SACEM_THEO_TRP_GLOBAL',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SACEM,
            RateType__c = OPAConstants.TARIF_REDUIT,
            OutcomeType__c = OPAConstants.OUTCOME_TARIF,
            AssociatedRateName__c = 'NUM_REDEV_SACEM_THEO_TRP_GLOBAL'
        ));
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_REDEV_SACEM',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SACEM,
            RateType__c = OPAConstants.TARIF_GENERAL,
            OutcomeType__c = OPAConstants.OUTCOME_TARIF,
            AssociatedRateName__c = 'NUM_REDEV_SACEM'
        ));
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_MT_SPRE',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SPRE,
            RateType__c = OPAConstants.TARIF_GENERAL,
            OutcomeType__c = OPAConstants.OUTCOME_TARIF,
            AssociatedRateName__c = 'NUM_MT_SPRE'
        ));
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_MT_HT_SACEM',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SACEM,
            RateType__c = OPAConstants.TARIF_GENERAL,
            OutcomeType__c = OPAConstants.OUTCOME_TARIF,
            AssociatedRateName__c = 'NUM_MT_HT_SACEM'
        ));
        lstObjectifs.add(new OfferOutcome__c(
            Name = 'NUM_MT_HT_SACEM_UTILE',
            Offer__c = offer.Id,
            Company__c = OPAConstants.COMPANY_SACEM,
            RateType__c = OPAConstants.TARIF_GENERAL,
            OutcomeType__c = OPAConstants.OUTCOME_REPARTITION,
            AssociatedRateName__c = 'NUM_MT_HT_SACEM'
        ));
        insert lstObjectifs;
        return lstObjectifs;

    }

    private static Offer__c createOffer() {
        return createOffer(false);
    }

    private static Offer__c createOffer(boolean complex) {
        Offer__c offer = new Offer__c(
            Name = 'Offre001',
            StartingDateValidity__c = Date.NewInstance(2020, 1, 1),
            PeriodicityOffer__c = 'Abonnement non renouvelable',
            CollectionFamily__c = 'Tous',
            TypeProcess__c = 'Prospection',
            ActivityAreas__c = OPAConstants.ACTIVITY_AREA_CASINO,
            LegalForm__c = 'Entreprise'
        );
        insert offer;
        
        List<Criterion__c> lstCriteres = createCriteria();
        if(complex) {
            lstCriteres.addAll(createSpaceCriteria());
            lstCriteres.addAll(createMoyenCriteria());
        }
        List<OfferCriterion__c> lstOfferCrit = new List<OfferCriterion__c>();
        for(Criterion__c critere: lstCriteres) {
            String critName = critere.LabelCriterion__c;
            String target = OPAConstants.TARGET_STANDARD;
            if(critName.startsWith('Espace')) {
                target = OPAConstants.TARGET_SPACE;
            } else if (critName.startsWith('Moyen')){
                target = OPAConstants.TARGET_MOYEN;
            }
            
            OfferCriterion__c offerCrit = new OfferCriterion__c (
                Offer__c = offer.Id,
                criterion__c = critere.Id,
                CriterionToSendToOPA__c = true,
                OPACriterionName__c = critName.toUpperCase() + '_OPA_CRIT',
                TargetCriterion__c = target               
            );
            lstOfferCrit.add(offerCrit);
        }
        insert lstOfferCrit;

        createObjectifs(offer);

        return offer;
    }

    public Static Asset createAuthorization() {
        return createAuthorization(false);
    }

    public static Asset createAuthorization(boolean complex) {
        Offer__c offer = createOffer(complex);
        Asset autorisation = new Asset (
            Name = 'Autorisation 001',
            CurrencyIsoCode = 'EUR',
            Offre__c = offer.Id 
        );
        insert autorisation;
        List<CriterionAuthorization__c> lstAutoCrit = new List<CriterionAuthorization__c>();
        List<OfferCriterion__c> lstOfferCrit = [
            SELECT Id, OPACriterionName__c, TargetCriterion__c, CriterionType__c
            FROM OfferCriterion__c
            WHERE Offer__c = :offer.Id
        ];

        List<BroadcastSpace__c> espaces = createEspaces(autorisation);
        List<WayDiffusion__c> moyens = createMoyensDiffusion(espaces);

        for(OfferCriterion__c offerCrit : lstOfferCrit) {
            String critValue = '';
            String critType = offerCrit.CriterionType__c;
            String critTarget = offerCrit.TargetCriterion__c;
            switch on offerCrit.OPACriterionName__c {
                when 'TEXTE_OPA_CRIT' {
                    critValue = 'AAA';
                }
                when 'NOMBRE_OPA_CRIT' {
                    critValue = '999';
                }
                when 'DATE_OPA_CRIT' {
                    critValue = '2020-01-01';
                }
                when 'BOOLEEN_OPA_CRIT' {
                    critValue = 'true';
                }
            }
            if(critValue <> '') {
                lstAutoCrit.add(new CriterionAuthorization__c (
                    CriterionResponseAuthz__c = critValue,
                    CriterionOffer__c = offerCrit.Id,
                    Authorization__c = autorisation.Id
                ));
            }
            if(critTarget == OPAConstants.TARGET_SPACE) {
                for(BroadcastSpace__c espace : espaces) {
                    critValue = (critType == OPAConstants.TYPE_NOMBRE)?'888':'BBB';
                    lstAutoCrit.add(new CriterionAuthorization__c (
                        CriterionResponseAuthz__c = critValue,
                        CriterionOffer__c = offerCrit.Id,
                        Authorization__c = autorisation.Id,
                        BroadcastSpace__c = espace.Id
                    ));
                }
            }
            if(critTarget == OPAConstants.TARGET_MOYEN) {
                for(WayDiffusion__c moyen : moyens) {
                    critValue = (critType == OPAConstants.TYPE_NOMBRE)?'777':'CCC';
                    lstAutoCrit.add(new CriterionAuthorization__c (
                        CriterionResponseAuthz__c = critValue,
                        CriterionOffer__c = offerCrit.Id,
                        Authorization__c = autorisation.Id,
                        WayDiffusion__c = moyen.Id
                    ));
                }
            }

        }

        insert lstAutoCrit;
        return autorisation;
    }


    public static OPAResponse createOPAResponse() {
        OPAResponse resp = new OPAResponse();
        OPAResponse.RateData rate;
        OPAResponse.RateLineData rateLine;
        
        rate = new OPAResponse.RateData();
        rate.Name = 'NUM_REDEV_SACEM_THEO_TG_GLOBAL';
        rate.ValueHT = 100.0;
        rateLine = new OPAResponse.RateLineData();
        rateLine.Name = 'OBJ_TG_LINE1' ;
        rateLine.ValueHT = 100.0;
        rateLine.Label = 'Tarif général : 100.0 EUR';
        rateLine.Level = 0;
        rateLine.EntityId = OPAConstants.ENTITY_TYPE_GLOBAL;
        rateLine.InstanceId = OPAConstants.ENTITY_TYPE_GLOBAL;
        rate.RateLines.add(rateLine);
        resp.rates.put(rate.Name, rate);

        rate = new OPAResponse.RateData();
        rate.Name = 'NUM_REDEV_SACEM_THEO_TR_GLOBAL';
        rate.ValueHT = 70.0;
        rateLine = new OPAResponse.RateLineData();
        rateLine.Name = 'OBJ_TR_LINE1' ;
        rateLine.ValueHT = 70.0;
        rateLine.Label = 'Tarif réduit 30% : 70.0 EUR';
        rateLine.Level = 0;
        rateLine.EntityId = OPAConstants.ENTITY_TYPE_GLOBAL;
        rateLine.InstanceId = OPAConstants.ENTITY_TYPE_GLOBAL;
        rate.RateLines.add(rateLine);
        rateLine = new OPAResponse.RateLineData();
        rateLine.Name = 'OBJ_TR_LINE2' ;
        rateLine.ValueHT = 100.0;
        rateLine.Label = 'Tarif général : 100.0 EUR';
        rateLine.Level = 1;
        rateLine.EntityId = OPAConstants.ENTITY_TYPE_GLOBAL;
        rateLine.InstanceId = OPAConstants.ENTITY_TYPE_GLOBAL;
        rate.RateLines.add(rateLine);
        resp.rates.put(rate.Name, rate);

        return resp;
    }





    
}