progressif/main/default/objects/BroadcastSpace__c/BroadcastSpace__c.object-meta.xml
<CustomObject>
    <label>Espace de diffusion</label>
    <nameField>
        <label>Nom de Espace de diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Espaces de diffusion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/CriterionAuthorization__c.object-meta.xml
<CustomObject>
    <label>Critère d&#39;autorisation</label>
    <nameField>
        <displayFormat>AUTCR-{0000}</displayFormat>
        <label>Nom du critère d’autorisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères d&#39;autorisation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/WayDiffusion__c.field-meta.xml
<CustomField>
    <fullName>WayDiffusion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Moyen de Diffusion</label>
    <referenceTo>WayDiffusion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization2</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/OfferOutcome__c/OfferOutcome__c.object-meta.xml
<CustomObject>
    <label>Objectif de l&#39;offre</label>
    <nameField>
        <label>Nom de l&#39;objectif de l&#39;offre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectifs de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/WayDiffusion__c.object-meta.xml
<CustomObject>
    <label>Moyen de Diffusion</label>
    <nameField>
        <label>Nom de Moyen de Diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moyens de Diffusion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Moyens de Diffusion</relationshipLabel>
    <relationshipName>ChildWayDiffusion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/classes/OPADAOTest.cls
@isTest
public with sharing class OPADAOTest {
    //Ces tests ont pour but de valider l'aspect statique des méthodes et la non répétition des 
    //requpetes SOQL

    @isTest
    public static void testMapAuthorizations() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<Id, Asset> myMap = OPADAO.mapAuthorizations;
        Map<Id, Asset> myOtherMap = OPADAO.mapAuthorizations;
        System.assertEquals(1, system.Limits.getQueries()); // La requête SOQL ne doit avoir été appelée qu'une fois
        test.stopTest();
        System.debug(myMap);
    }

    @isTest
    public static void testMapSpaces() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<Id, BroadcastSpace__c> myMap = OPADAO.mapSpaces;
        Map<Id, BroadcastSpace__c> myOtherMap = OPADAO.mapSpaces;
        System.assertEquals(1, system.Limits.getQueries()); // La requête SOQL ne doit avoir été appelée qu'une fois
        test.stopTest();
        System.debug(myMap);
    }

    @isTest
    public static void testMapWaysDiffusion() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<Id, WayDiffusion__c> myMap = OPADAO.mapWaysDiffusion;
        Map<Id, WayDiffusion__c> myOtherMap = OPADAO.mapWaysDiffusion;
        Map<Id, BroadcastSpace__c> MySpacesMap = OPADAO.mapSpaces;
        System.assertEquals(2, system.Limits.getQueries()); 
        // ways diffusion fait un premier appel à mapSpaces. Il y a donc deux requpetes SOQL
        // l'appel à mapSpaces vérifie que l'on ne recrée pas cette map à nouveau.
        test.stopTest();
        System.debug(myMap);
    }


    @isTest
    public static void testMapOfferIdByAuthorizationId() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<Id, Id> myMap = OPADAO.mapOfferIdByAuthorizationId;
        Map<Id, Id> myOtherMap = OPADAO.mapOfferIdByAuthorizationId;
        System.assertEquals(1, system.Limits.getQueries()); // La requête SOQL ne doit avoir été appelée qu'une fois
        test.stopTest();
        System.debug(myMap);
    }

    @isTest
    public static void testMapLstOutcomesByOfferId() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<Id, List<OfferOutcome__c>> myMap = OPADAO.mapLstOutcomesByOfferId;
        Map<Id, List<OfferOutcome__c>> myOtherMap = OPADAO.mapLstOutcomesByOfferId;
        Map<Id, Id> myOfferMap = OPADAO.mapOfferIdByAuthorizationId;
        System.assertEquals(2, system.Limits.getQueries()); 
        // Fait un premier appel à mapOfferIdByAuthorizationId. Il y a donc deux requpetes SOQL
        // l'appel à mapOfferIdByAuthorizationId vérifie que l'on ne recrée pas cette map à nouveau.
        test.stopTest();
        System.debug(myMap);
    }

    @isTest
    public static void testMapOutcomesByName() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<String, OfferOutcome__c> myMap = OPADAO.mapOutcomesByName;
        Map<String, OfferOutcome__c> myOtherMap = OPADAO.mapOutcomesByName;
        Map<Id, Id> myOfferMap = OPADAO.mapOfferIdByAuthorizationId;
        System.assertEquals(2, system.Limits.getQueries()); 
        // Fait un premier appel à mapOfferIdByAuthorizationId. Il y a donc deux requpetes SOQL
        // l'appel à mapOfferIdByAuthorizationId vérifie que l'on ne recrée pas cette map à nouveau.
        test.stopTest();
        System.debug(myMap);
    }

    @isTest
    public static void testMapAuthorizationCriteriaByAuthorizationId() {
        Id autorisationId = OPADataFactory.createAuthorization(true).Id;
        OPADAO.setAuthorizationId(autorisationId);

        test.startTest();
        Map<Id, List<CriterionAuthorization__c>> myMap = OPADAO.mapAuthorizationCriteriaByAuthorizationId;
        Map<Id, List<CriterionAuthorization__c>> myOtherMap = OPADAO.mapAuthorizationCriteriaByAuthorizationId;
        System.assertEquals(1, system.Limits.getQueries()); // La requête SOQL ne doit avoir été appelée qu'une fois
        test.stopTest();
        System.debug(myMap);
    }
}