progressif/main/default/objects/BroadcastSpace__c/BroadcastSpace__c.object-meta.xml
<CustomObject>
    <label>Espace de diffusion</label>
    <nameField>
        <label>Nom de Espace de diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Espaces de diffusion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/CriterionAuthorization__c.object-meta.xml
<CustomObject>
    <label>Critère d&#39;autorisation</label>
    <nameField>
        <displayFormat>AUTCR-{0000}</displayFormat>
        <label>Nom du critère d’autorisation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères d&#39;autorisation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/CriterionAuthorization__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionOffer__c.field-meta.xml
<CustomField>
    <fullName>CriterionOffer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Critère de l&#39;offre</label>
    <referenceTo>OfferCriterion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>Criterion_of_the_offer_child</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/CriterionResponseAuthz__c.field-meta.xml
<CustomField>
    <fullName>CriterionResponseAuthz__c</fullName>
    <label>Réponse de critère</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

progressif/main/default/objects/CriterionAuthorization__c/fields/WayDiffusion__c.field-meta.xml
<CustomField>
    <fullName>WayDiffusion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Moyen de Diffusion</label>
    <referenceTo>WayDiffusion__c</referenceTo>
    <relationshipLabel>Critères d&#39;autorisation</relationshipLabel>
    <relationshipName>ChildCriterionAuthorization2</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/objects/OfferCriterion__c/OfferCriterion__c.object-meta.xml
<CustomObject>
    <label>Critère de l&#39;offre</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Numéro de Critère</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critères de l&#39;offre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/WayDiffusion__c.object-meta.xml
<CustomObject>
    <label>Moyen de Diffusion</label>
    <nameField>
        <label>Nom de Moyen de Diffusion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moyens de Diffusion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

progressif/main/default/objects/WayDiffusion__c/fields/BroadcastSpace__c.field-meta.xml
<CustomField>
    <fullName>BroadcastSpace__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Espace de diffusion</label>
    <referenceTo>BroadcastSpace__c</referenceTo>
    <relationshipLabel>Moyens de Diffusion</relationshipLabel>
    <relationshipName>ChildWayDiffusion</relationshipName>
    <type>Lookup</type>
</CustomField>

progressif/main/default/classes/OPARequestBodyTest.cls
@IsTest
public without sharing class OPARequestBodyTest {

    @IsTest 
    public static void testBodyCreation() {
        Asset autorisation = OPADataFactory.createAuthorization();
        System.debug(autorisation);
        OPADAO.setAuthorizationId(autorisation.Id);

        Test.startTest();
        String body = OPARequestBody.create(autorisation.Id);
        Test.stopTest();

        System.debug(body);

        Map<String, Object> bodyObj = (Map<String, Object>)JSON.deserializeUntyped(body);

        // Vérification des critères
        /*
        List<Object> cases = (List<Object>)bodyObj.get('cases');
        Map<String, Object> criteres = (Map<String, Object>)cases[0];
        System.debug(criteres);
        System.assertEquals('AAA', (String)criteres.get('TEXTE_OPA_CRIT'));
        System.assertEquals(999.0, (Double)criteres.get('NOMBRE_OPA_CRIT'));
        System.assertEquals('2020-01-01', (String)criteres.get('DATE_OPA_CRIT'));
        System.assert((Boolean)criteres.get('BOOLEEN_OPA_CRIT'));

        // Vérification des objectifs
        List<Object> outcomes = (List<Object>)bodyObj.get('outcomes');
        System.debug(outcomes);
        System.assert(outcomes.contains('OBJ_TR'));
        System.assert(outcomes.contains('OBJ_TG'));
        */
    }

    @isTest
    public static void testComplexBodyCreation() {
        Asset autorisation = OPADataFactory.createAuthorization(true);
        System.debug(autorisation);

        for(CriterionAuthorization__c critere : [
            SELECT Id, Name, CriterionResponseAuthz__c, BroadcastSpace__r.Name, WayDiffusion__r.Name, CriterionOffer__r.Name
            FROM CriterionAuthorization__c
            ]) {
                System.debug(critere);
        }
        OPADAO.setAuthorizationId(autorisation.Id);

        Test.startTest();
        String body = OPARequestBody.create(autorisation.Id);
        Test.stopTest();

        System.debug(body);

        Map<String, Object> bodyObj = (Map<String, Object>)JSON.deserializeUntyped(body);

        // Vérification des critères
        /*
        List<Object> cases = (List<Object>)bodyObj.get('cases');
        Map<String, Object> criteres = (Map<String, Object>)cases[0];
        System.debug(criteres);
        System.assertEquals('AAA', (String)criteres.get('TEXTE_OPA_CRIT'));
        System.assertEquals(999.0, (Double)criteres.get('NOMBRE_OPA_CRIT'));
        System.assertEquals('2020-01-01', (String)criteres.get('DATE_OPA_CRIT'));
        System.assert((Boolean)criteres.get('BOOLEEN_OPA_CRIT'));

        // Vérification des objectifs
        List<Object> outcomes = (List<Object>)bodyObj.get('outcomes');
        System.debug(outcomes);
        System.assert(outcomes.contains('OBJ_TR'));
        System.assert(outcomes.contains('OBJ_TG'));
        */
    }
}